### ISSUE TITLE
Inconsistent times displayed on View Seminar page

### ISSUE THREAD

**Issue by AndrewVSutherland** [roed314/seminars#10]
On "View Seminar" pages like https://mathseminars.org/seminar/ComplexGeometry, the time for the seminar is based on the time zone of the seminar (which is not displayed) while the time zone of the talk is based on the viewer's time zone.  This is very confusing (so confusing that I consider it a bug, a person looking at this page has no idea what  time the talks are).

I think the best thing to do would be to display the time zone of the seminar and display the time in both the seminar and viewer time zones (e.g. captioned "Seminar time" and "Your time").  We should also indicate that the talks are in the viewer's time zone, perhaps by changing the date/time header to "Your time".

**Comment by roed314** [comment]
I've addressed part of this issue: times are now displayed correctly in the user's time zone.

**Comment by roed314** [comment]
Switching to enhancement: we should display both the seminar time and the user's time when showing a seminar/talk homepage.

**Comment by roed314** [comment]
I think this is now resolved by #50.  @AndrewVSutherland, if you agree, go ahead and close this issue.

**Comment by AndrewVSutherland** [comment]
I think it is okay as is (certainly XX:XX in your timezone: AAA is crystal clear), but I note that it is only displaying the user's time, it does not show the seminar time, contrary to what you wrote above; is that the intention?  

One reason to also display the seminar time zone would be for consistency with the external seminar page which the user can reach by clicking the seminar title.  Also, once we return to a world in which some seminars take place at physical locations, the seminar time will be more relevant.
