### ISSUE TITLE
Possible to lock out from own seminar

### ISSUE THREAD

**Issue by ddorian1** [roed314/seminars#103]
If you create a Seminar and by accident (or ignorance of the consequences) remove all e-mail addresses in the organizer section, there is no possibility to edit the seminar any more.
When trying to do so, you are told to contact the seminar owner (i.e. yourself) to grant you permission, what's impossible.

**Comment by AndrewVSutherland** [comment]
This is bug, the user who created the seminar should always be able to edit it, but as I just confirmed, this is not the case.

I will be submitting a PR shortly that, among other things, won't let you save a seminar without at least one email listed, but that doesn't change the fact that we need to fix this bug.

**Comment by edgarcosta** [comment]
@ddorian1, can you tell me the seminar?

**Comment by edgarcosta** [comment]
@ddorian1, also did you change your email meanwhile?

**Comment by ddorian1** [comment]
Se seminar in question is https://mathseminars.org/seminar/BISTRO.
As it was still pretty empty, I recreated it as https://mathseminars.org/seminar/BISTRO-Seminar. So feel free to delete the old one (https://mathseminars.org/seminar/BISTRO).
And yes, I changed my email. Sorry if that complicates matters.

**Comment by edgarcosta** [comment]
@AndrewVSutherland, the issue is that we are storing the user's email, not id, in the seminar db

**Comment by ddorian1** [comment]
Just to clarify: I was already locked out of the seminar **before** I changed my email.
