### ISSUE TITLE
Embeddable schedule

### ISSUE THREAD

**Issue by tornaria** [roed314/seminars#104]
A useful feature would be a page for each seminar with only the schedule, so it can be embedded in the seminar "external" homepage (+ sample code to paste into html).

The point is: I don't want to update the list of talks twice, and the mathseminars interface is so nice...

**Comment by AndrewVSutherland** [comment]
@tornaria This is a great idea (and easy to do).  You can also achieve this using an embedded  calendar, but I think this a simpler and better approach.

Anything we can do to make it easier for seminar organizers to maintain their listings on mathserminars.org without having to enter data twice is a high priority for us.

**Comment by roed314** [comment]
We have a first draft of this.  See https://mathseminars.org/seminar_raw/LATeN for example.

**Comment by AndrewVSutherland** [comment]
It would be good to have separate links for page and future talks (you might only want to show future talks, or to show the past and future talks on different parts of your web page/site).

**Comment by tornaria** [comment]
Looks good.

My css-fu is not very good, if I `<embed>` as is I get a small widget with scrollbars. I put `width=100%` which is kind of ok for horizontal, but for height I had to hardcode a size and if it's too large I get empty space after the embed, if too small, vertical scrollbar. If I find the perfect height it looks great.

I'm sorry I can't be of more help with this :-(

My ideal would be some html/js block that I paste in my web.page and gives me some reasonable look, and it'd be really nice if I can actually style it with my own css. Then I could put "hidden" on the past talks if I only want future talks, etc. Maybe all of this is easier to do via raw json that one can use in arbitrary way.

**Comment by edgarcosta** [comment]
@tornaria, I'm planning to work more on this to a bit more to make it easier to include as an iframe.

> Maybe all of this is easier to do via raw JSON that one can use in an arbitrary way.
I believe that is exactly why @kedlaya started #11.

**Comment by edgarcosta** [comment]
I've reworked the framework:
Here are some examples to try out:
```
<iframe src="https://master.mathseminars.org/seminar/DG_methods/raw" style="border: 0" width="800" height="100%" frameborder="0" scrolling="no"></iframe>
<iframe src="https://master.mathseminars.org/seminar/LATeN/raw?past=" style="border: 0" width="800" height="100%" frameborder="0" scrolling="no"></iframe>
<iframe src="https://master.mathseminars.org/seminar/LATeN/raw?future=" style="border: 0" width="800" height="100%" frameborder="0" scrolling="no"></iframe>
<iframe src="https://master.mathseminars.org/seminar/LATeN/raw?daterange=May+14%2C+2020+-+May+21%2C+2020" style="border: 0" width="800" height="100%" frameborder="0" scrolling="no"></iframe>
```


```

**Comment by tornaria** [comment]
Thanks, it kind of works, and looks nice:

http://www.cmat.edu.uy/~tornaria/LATeN/embed/

It still has the issue with the height -- I have to hardcode it. Moreover, when you try to open a knowl, if that "overflows" the frame it won't be displayed (I guess that's expected, but it makes the feature not very usable).

**Comment by roed314** [comment]
This seems like it might be relevant to the height issue: https://stackoverflow.com/questions/9162933/make-iframe-height-dynamic-based-on-content-inside-jquery-javascript

**Comment by edgarcosta** [comment]
I will look into it.
However, what @kedlaya did with #11 seems a better solution overall.

**Comment by edgarcosta** [comment]
I've been trying to play the CSS game and I lost.
I will just write some javascript that loads the content and displays it, very similar to what @kedlaya did, but on the client-side.
I realized that the CGI route is not very beginner-friendly.

**Comment by kedlaya** [comment]
CGI is a lot easier the second time you set it up. I went through most of the pain once already setting up https://kskedlaya.org/confs.cgi.

**Comment by edgarcosta** [comment]
I agree. However, not every server supports CGI, and if so one would need to convince them to change their file extension, permissions and etc...
and I would like the embeddable schedule to be as easy as copy-pasting a couple lines of code.

**Comment by edgarcosta** [comment]
@tornaria, here is a different approach with java script.
```
<div class="embeddable_schedule" shortname="LATeN" daterange="April 23, 2020 - April 29, 2020" format="MMMM D"></div>
<div class="embeddable_schedule" shortname="LATeN" daterange="past"></div>
<div class="embeddable_schedule" shortname="LATeN" daterange="future"></div>
<script src="https://master.mathseminars.org/embeddable_schedule.js" onload='embed_schedule();'></script>
```
I need to add styling file, so the table doesn't look so bad, but what do you think about it?

**Comment by edgarcosta** [comment]
@duetosymmetry, this is the issue that I was talking about.
The JS is all in `seminars/templates/seminar_raw.js`

**Comment by duetosymmetry** [comment]
@edgarcosta I guess I'm supposed to be looking at branch `newcalendar`?

Can you explain why you prefer a JS solution to using an iframe? I just feel like the pure JS approach ends up repeating a bunch of code.

BTW instead of passing parameters to the JS via DOM attributes, which JS then has to parse, a simpler approach is to precede the main script with a short snippet which just sets JS variables (e.g. MathJax is configured like this). Presumably this user will just copy/paste a generated code block so they won't have to actually write the JS.

**Comment by edgarcosta** [comment]
@duetosymmetry, it's already on master.

I agree I repeated a bunch of code.
The iframe has some issues:
- the size doesn't adjust accordingly when we show an abstract or more
- you get the cookie popup
- user's can't style their own table

The JS solution creates a table on their website, so they can style it themselves, and content height will fit accordingly.

**Comment by edgarcosta** [comment]
Regarding, the arguments, you are most likely right, but having the arguments in DOM, allows users to have different arguments in different places.

**Comment by duetosymmetry** [comment]
@edgarcosta the special embedding URLs could avoid setting cookies and thus not need to show the cookie popup (I think Google Calendar's embed pages do this).

If you are going to use javascript in this solution, it could be simpler to make the job of the javascript code to size the iframe appropriately.

Alternately, if javascript is going to fetch something and add it to the page, it could fetch HTML (XML) instead of JSON, and just add the pre-built table into some target div.

I think what you're getting at with the arguments in DOM vs JS: this need not be a single global variable, but rather an options object passed to a single JS function to request said calendar.

Let me know if you'll be working on this today or tomorrow, please let me know and we can chat in real time instead of on this issue.

**Comment by edgarcosta** [comment]
We can talk tomorrow or Monday. I won't work on this today.

**Comment by duetosymmetry** [comment]
@edgarcosta I started working on overhauling this to simplify it, [here](https://github.com/duetosymmetry/seminars/commit/9b7e01f46c03ce95801d1adab913d06326307189). For KaTeX, it will be straightforward to (1) detect if KaTeX is already present on the embedding page, (2) insert script and link tags for it if needed. For the `knowl="dynamic_show"` handling, though, I think we should break out that code from `lmfdb.js`. That way it can be preloaded or dynamically loaded on the embedder's page, without loading all the other machinery. I don't know much about the dynamic_show code, do you want to chat at some point?

**Comment by edgarcosta** [comment]
@duetosymmetry, this looks very promising and much better than the spaghetti code that I wrote.

I have just submitted a PR to LMFDB to fix their knowl code, once they merge it, we can just load `lmfdb.js` with `{{ url_for('static', filename='lmfdb.js', _external=True, _scheme=scheme) }}`

I agree with you, at the moment, we use very little of `lmfdb.js`, and even the knowl code can be simplified tremendously, as we are only using static knowls, the generic code is meant to fetch to load them through a request.

**Comment by duetosymmetry** [comment]
I've got code to make embed-code and copy-to-clipboard [here](https://github.com/duetosymmetry/seminars/commit/dcb364a4fb3c976c4e43119de8686c0e5c416cf7). Almost feature complete, 1 issue to work out on the server side, and then getting the dynamic_show knowl code onto the client page.

**Comment by edgarcosta** [comment]
For the time being, one can just include: https://researchseminars.org/lmfdb.js

**Comment by edgarcosta** [comment]
I have also just updated the submodule commit to point to the new lmfdb.js

**Comment by duetosymmetry** [comment]
But `lmfdb.js` relies on jquery, right? I was trying to avoid having this dependency.

**Comment by edgarcosta** [comment]
Yes! One solution is to rewrite it without jquery, and then we can almost purge `lmfdb.js`

**Comment by edgarcosta** [comment]
@tornaria, please check out our new emebedabble schedule at:

https://master.mathseminars.org/seminar/LATeN

I still need to create a minimal and generic css file, but please let me know if this makes sense.

**Comment by tornaria** [comment]
This looks amazing. It took me 2 minutes to put it in my page (http://www.cmat.edu.uy/~tornaria/LATeN/embed/ for a test).

I found two quirks regarding links. When you open the knowl for a talk, the "view" link for the talk and the seminar link, are linked without hostname so they are broken. The calendar links seem to be ok.

A sugestion: maybe place a "powered by mathseminars.org" line at the bottom of the displayed schedule, that way I don't even have to worry about giving you guys credit.

Thanks a lot!

**Comment by duetosymmetry** [comment]
@tornaria Thanks for reporting this, I have a bugfix. I've only tested it a little bit, I'd appreciate it if somebody else would look over my code, in PR #348

**Comment by roed314** [comment]
I've merged the PR, so it should now be live on @tornaria's site.

I think the "powered by researchseminars.org" suggestion is interesting, if we give people the option to turn it off.  We already advertise a bit by the fact that the view talk link goes back to researchseminars.org.

**Comment by duetosymmetry** [comment]
The optional footer is an easy addition, I can work on this right now.
BTW do you think we should allow further options at load time, e.g. whether or not to process katex and whether or not to process knowls?

**Comment by duetosymmetry** [comment]
@roed314 Implemented in PR #353. @tornaria If this is merged in, you will be able to add the footer to a given embedded schedule by adding the `sitefooter` attribute to the `<div>` tag, e.g.
```
<div class="embeddable_schedule" shortname="LATeN" daterange="past" sitefooter></div>
```

BTW @tornaria on your example page, you only need the `<script>` tag one time, not two.

**Comment by tornaria** [comment]
This is looking great!

Note: the css overrides the style for my webpage. It would be nice if it only applied to the schedules. Can you please use a separate style for embedded schedules that prepends every entry with `div.embedded_schedule` so everything applies just to the schedule?

As a quick hack I got a (possibly buggy) css with this awk:
```
curl https://master.mathseminars.org/style.css  |
  awk -e 'BEGIN{SEL="div.embedded_schedule"}
        !inside&&!done&&!/^$/&&!/^\/\*.*\*\/$/ {printf "%s ",SEL;done=1}
        !inside {gsub(",",",\n"SEL" ")}
        /{/ {inside++}
        /}/ {done=--inside}
        {print}' > embed_seminars.css
```

**Comment by edgarcosta** [comment]
We need to write a minimal css file for this.

**Comment by duetosymmetry** [comment]
I think this is possible if we use a jinja template to generate the CSS. CSS doesn't support nesting (it's in draft AFAIK) but SASS does, so we could process the jinja template to produce SASS, then hand it to libsass-python. Does this sound like overkill?

**Comment by edgarcosta** [comment]
I think that is overkill, but perhaps useful for a first approach.
Our stylesheet at the moment is also overkill, as only use a very small
amount of it.
However, for embeddable schedules, we should really aim to provide a
minimal stylesheet, with the blue shading replaced by something more
neutral, that allows users to copy and modify.
Our stylesheets are templates, so there will be some repetition of css
code, but colors and what not can all be set through the python.

**Comment by duetosymmetry** [comment]
Ok, I agree it will end up being simpler to strip down the style sheet to only the parts that are used for the embedding of the table.

**Comment by tornaria** [comment]
For the record, our seminar page at http://www.cmat.edu.uy/~tornaria/LATeN/ uses embeded schedules with two hacks:
a. modify the mathseminars css so it only applies to the schedules
b. some javascript that changes the table headings
In the end, I think it will be much more flexible for me to use #11, but the json now is missing paper/video/slides link.

But really for a first version this embedded schedule is awesome. And so easy to do with clear instructions!

I think the only missing part so this is complete is using a separate minimal css that prepends every entry with `div.embedded_schedule` so it doesn't override the site css and it's easy to change incrementally.

**Comment by edgarcosta** [comment]
You make very good points. 
I will try to fix the last issues tomorrow.

**Comment by edgarcosta** [comment]
@tornaria, sorry it took me so long, but I have fixed our code to use a minimal css, that does not affect the rest of the website:
Here is an example,
https://math.mit.edu/~edgarc/ucsd.html
let me know what you think

**Comment by tornaria** [comment]
Nice, thanks.

Some comments / suggestions:
1. maybe insert css at beginning of head so it can be overriden by site css, e.g.
```diff
-    head.appendChild(link);
+    head.insertBefore(link, head.firstChild);
```

2.  in `*[knowl]:hover`, maybe use `--link-hover-color` instead of `--link-color`, e.g.

```diff
-    border-bottom: 2px solid var(--link-color);
+    border-bottom: 2px solid var(--link-hover-color);
```
```diff
-    color: var(--link-color);
+    color: var(--link-hover-color);
```

3. minor adjustements:
```diff
-div.embedded_schedule *[knowl]:hover, *[knowl].active {
+div.embedded_schedule *[knowl]:hover,
+div.embedded_schedule *[knowl].active {
```
```diff
-div.embedded_schedule div > *[knowl], p > *[knowl] {
+div.embedded_schedule div > *[knowl],
+div.embedded_schedule p > *[knowl] {
```

4. it seems times are shown in UTC (?)

**Comment by roed314** [comment]
For the time zone, I assume we should default to the series' time zone.  Should it be possible to override this, e.g. `<div class="embeddable_schedule" shortname="MITNT" timezone="US/Pacific" daterange="past">`?

**Comment by kedlaya** [comment]
I can see a use case for this: if I am doing a joint seminar with an institution in another time zone, one of them has to be the home time zone, but the other would like to be able to display the schedule in its time zone.

**Comment by edgarcosta** [comment]
@tornaria Thank you
I will get on this shortly

**Comment by tornaria** [comment]
@edgarcosta thanks a lot for all your work!

For me this is good and working, and very useful. I think this ticket is ready to close. If anything is missing is the three minor suggestions in my previous comment (https://github.com/roed314/seminars/issues/104#issuecomment-629949144) of which the more important is the first one (the rest can be overriden by css).

---

Just one final comment, in case it's useful. I've been trying to make the table to look ok in a phone, and I've finally found out one reasonable way (see http://www.cmat.edu.uy/~tornaria/LATeN/).

Two things required:
 a. place the following in the `<head>`
```html
<meta name="viewport" content="width=device-width initial-scale=1">
```
 b. eliminate `min-width` values that come in the standard `embed_seminar.css`, e.g. with this css:
```
div.embedded_schedule table.ntdata td.speaker {
  min-width: 0;
}

div.embedded_schedule table.ntdata td.talktitle {
  min-width: 0;
}
```
The table looks reasonably ok in my phone now (but only because I only print a short date and no time in the date column).

I wonder if it would make sense to *not* have the `min-width` properties in `embed_seminar.css`. No big deal, since it can be adjusted in the css.

**Comment by AndrewVSutherland** [comment]
@edgarcosta Are we ready to close this?  We can always create new issues for specific problems or feature requests, but it sounds like the essential functionality is now available.

**Comment by edgarcosta** [comment]
I have addressed all the issues, and we now support different timezones.
See:
https://math.mit.edu/~edgarc/ucsd.html

these changes will be available on the live website.
