### ISSUE TITLE
Add JSON retrieval

### ISSUE THREAD

**Issue by kedlaya** [roed314/seminars#11]
It would be useful to extract data via an RSS feed, in order to make a front end. More precisely, I'd like to be able to search by:
  - Date range
  - Seminar name or ID (optional)

and get back:
 - Date
 - Time
 - Speaker
 - Title
 - Abstract

**Comment by MaxAVF** [comment]
I also think this would be a great feature, I was thinking about using the rss feed to create a Twitter bot that would tweet about upcomings seminars/talks.

**Comment by kedlaya** [comment]
I should add: MathMeetings also provides an API with options to retrieve JSON or XML in addition to RSS. I'd be satisfied with any of them.

**Comment by edgarcosta** [comment]
@kedlaya, would a single JSON with all the talks (in the specified range) would sufficient?

**Comment by kedlaya** [comment]
Absolutely yes!

**Comment by kedlaya** [comment]
Here's what I did with it: https://kskedlaya.org/nts.cgi

In my wish list, I appear to have forgotten speaker affiliation.

**Comment by MaxAVF** [comment]
There is a json file for every seminar group? or there is a way to get a json with the data of all the seminars?

**Comment by edgarcosta** [comment]
@kedlaya, I have added a speaker affiliation and homepage. Also, can you share your code? as a cgi version is much better than an embeddable schedule

@MaxAVF, tell me what you want, and I see what I can do about it, at the moment, I don't really want to write a full API.

**Comment by MaxAVF** [comment]
@edgarcosta Having  a json file (json, xml, whatever) with the info of all the talks, so I dont thave to search though all the pages to collect small json files.

**Comment by kedlaya** [comment]
One more field I just realized I want: link to the speaker's slides.

**Comment by AndrewVSutherland** [comment]
@kedlaya In addition to the slides_link column, there is a paper_link and a video_link (for the recorded video not the livestream), which you might conceivable want.  You can see all three on

https://mathseminars.org/talk/vantage/8/

for example.

**Comment by roed314** [comment]
I am working on this as part of #96.

**Comment by tornaria** [comment]
> @kedlaya In addition to the slides_link column, there is a paper_link and a video_link (for the recorded video not the livestream), which you might conceivable want.

I think those three are all I would be missing in switching from embedded schedules (as in #104) to creating my own schedule using json data.

Maybe two more:
- the link to the actual talk in mathseminars.org
- the link to the ics for the talk

**Comment by edgarcosta** [comment]
While we don't have a full API, we now return:
```
[
        'speaker',
        'video_link',
        'slides_link',
        'title',
        'room',
        'comments',
        'abstract',
        'start_time',
        'end_time',
        'speaker_affiliation',
        'speaker_homepage',
        'language',
        'deleted',
        'paper_link',
        'stream_link',
    ]
```

**Comment by kedlaya** [comment]
Thanks. I'm now using 'paper_link' and 'slides_link' to create links on my page, and also 'comments' to determine whether or not to list a pre-talk.

**Comment by roed314** [comment]
@MaxAVF There is now more of an API at researchseminars.org/api.  I'm closing this issue in favor of tracking things further at #96.
