### ISSUE TITLE
talk link doesn't work

### ISSUE THREAD

**Issue by edgarcosta** [roed314/seminars#125]
reported by @tornaria

Here are the steps (still broken):
1. open a private window in firefox (to make sure I'm not logged in,
also uMatrix is disabled just in case)
2. paste the link into the address bar
3. type something into the "abstract" box (I just typed "a")
4. hit "save"
This yields the error I reported.

As a matter of fact, even skipping 3 gives the error.

The same happens in a regular window of chromium 81 (which I use only
for jitsi so it doesn't have any plugins).

(see form for the precise link)

**Comment by roed314** [comment]
Fixed.
