### ISSUE TITLE
Confusion at seminar creation

### ISSUE THREAD

**Issue by edgarcosta** [roed314/seminars#131]
@tornaria reported
> When creating a seminar for the field "institution" it gives me a message that I can add an institution before or after creating the seminar. However, I don't see how to do it. My guess is that I can't until i'm endorsed, but this is not mentioned anywere -- it'd be nice to clarify it.

**Comment by poonen** [comment]
Sorry, I had forgotten that users could create a seminar before they had permission to create an institution.  I updated the text on the "manage" page.

**Comment by AndrewVSutherland** [comment]
PR #152 (now live on master) makes some further progress on this.  I'm happy to make further changes, and if/when people are happy we can close this issue.

**Comment by AndrewVSutherland** [comment]
#152 and further improvements made by @poonen are now live, closing.
