### ISSUE TITLE
Reorganize organizers

### ISSUE THREAD

**Issue by edgarcosta** [roed314/seminars#132]
reported by @tornaria
> The order of the list of organizers is important (since it's the order of display) hence it'd be nice to be able to reorder them. This is obviously low priority if nontrivial, of course I just reordered by copy-pasting.

**Comment by poonen** [comment]
Buttons for doing adjacent transpositions might suffice, since usually the list of organizers is not so huge (and I think we all know that they generate S_n!).  Already that would be a lot better than copy-pasting.

**Comment by poonen** [comment]
1. Would it possible to shift each arrow upward by half a row, and to make it a bidirectional arrow, to indicate transposition of the two rows?  If that's too hard to do, it's OK to leave as is.

2. I find it quite annoying that each time I click one of these arrows, I am taken to the top of the page and have to scroll down before I can click another arrow.  If there were some way to keep the page in roughly the same position, then I could visibly see the change being done as I clicked each arrow.

**Comment by AndrewVSutherland** [comment]
@poonen I think I was able to achieve both 1 and 2 (at least in my browser), but take a look on master and let me know what you think.

**Comment by poonen** [comment]
It looks great to me!
