### ISSUE TITLE
Sort seminars in search results by their next talk

### ISSUE THREAD

**Issue by roed314** [roed314/seminars#133]

**Comment by rbommel** [comment]
Would it be an idea to prioritise seminars which are favourited?

**Comment by poonen** [comment]
I like rbommel's idea.  I suppose that specifically this means that (for logged-in users) all the favorited seminars would appear first, in order of their next talk, and then all the non-favorited seminars would appear in order of their next talk.

Alternatively, one could give favorited talks a smaller bonus, say by subtracting 7 days from the time of their next talk, and then ordering by this modified "next talk time".

**Comment by edgarcosta** [comment]
I dislike the idea of sorting by favorited, as when I go search/browse seminars, it is mostly because I'm looking for something that is not on my favorites.

Otherwise, I could just head to my account page.

**Comment by AndrewVSutherland** [comment]
I assume we are only talking about potentially prioritizing seminars that the logged in user has added to their favorites (this is clear in @poonen's post but not in @rbommel's).  I definitely don't think we should have the sort order depend on how many people have added a seminar to their favorite (people are likely to start gaming the system).

Maybe a compromise between what @poonen and @edgarcosta are saying would be to have a toggle on the browse seminar page that appears only to logged in users that allows you to include only favorites or everything.  I would find this more useful than having to click away to my account page, and the only downside I see is the minor clutter of having another toggle on the screen.

**Comment by rbommel** [comment]
Yes, I was thinking about your own favourites. Maybe I am looking for the MIT number theory seminar quickly, and I search for number theory instead of using my personal page. Then what David is suggesting is that the order of my results depend on the day on which I perform the search, which I understand for conferences, but less for seminars. I think people are slightly more likely to look for things they already favourited, even though there are other ways of finding it.

**Comment by edgarcosta** [comment]
I like Drew's compromise. We already have the code for that.

**Comment by roed314** [comment]
I'm going to leave the compromise to another issue, since I think there's more discussion to be had if we're going to be including the filters on the search page in addition to the browse page.  Unless Drew is just proposing another search input?  The values of search inputs are not saved across visits to the Search page, unlike the filters on the browse page which are saved in cookies.

**Comment by edgarcosta** [comment]
I agree that filtering by saved is not a high priority at the moment.

**Comment by roed314** [comment]
I've created a followup issue, and master.mathseminars.org currently has seminar search results sorted by next talk.  Once we merge into live we can close this issue.

**Comment by AndrewVSutherland** [comment]
@roed314 I was just thinking of another search input, not something that would be saved.  I think the default should be all talks, but we could add a toggle that (for that search only) just shows the talks in your favorites list.  I could imagine switching back and forth but if I leave the page and come back I would expect to see everything again.

**Comment by AndrewVSutherland** [comment]
@roed314 But I also agree this is not a high priority, I would focus on the 6 open high priority issues first (although it looks like you at least partially addressed the private seminars/talks issue?)
