### ISSUE TITLE
When creating a talk fails no flash message displays

### ISSUE THREAD

**Issue by alexjbest** [roed314/seminars#14]
When a user creates a talk in the edit schedule page that fails to create (I've seen this when no speaker or anything is listed) clicking save does nothing, the page refreshes but the talk is not saved, we should flash an error message here.

**Comment by edgarcosta** [comment]
I believe this is fixed

**Comment by edgarcosta** [comment]
@alexjbest, can you check that is indeed fixed?

**Comment by alexjbest** [comment]
Sortof! If I change one of the existing pre-filled dates in schedule to a new day and click save still nothing happens (it warns if one changes the time), maybe this is fine. But if a user goes to the trouble of writing something in and clicks save I think the warning "Warning: Talks are only saved if you specify a speaker" should be shown then too.

**Comment by edgarcosta** [comment]
if he writes something on any other field he will get a message.
notcing changes on prefilled fields is possible, but is a pain in the but, as we need to track what we filled them with...

**Comment by alexjbest** [comment]
Sounds fine for now then! This was only a behaviour I noticed when being lazy testing another feature so it seems unlikely this will cause any issues for users in the present state.
