### ISSUE TITLE
Edit date/time in "Edit schedule page"

### ISSUE THREAD

**Issue by AndrewVSutherland** [roed314/seminars#15]
When editing the schedule for a seminar or conference, it would be nice to be able to edit the date/time directly in the schedule rather than having to go edit each talk individually.  This would be especially useful for conferences (see https://mathseminars.org/edit/schedule/?shortname=Wagon) for an example.

**Comment by roed314** [comment]
See #32

**Comment by AndrewVSutherland** [comment]
Addressed by #32
