### ISSUE TITLE
"deleted" = false OR "deleted" IS NULL

### ISSUE THREAD

**Issue by edgarcosta** [roed314/seminars#150]
@roed314, can we replace NULLs by falses?

**Comment by AndrewVSutherland** [comment]
Yes, but we still want this in the code as a backstop.  This is exactly what broke things last night.

**Comment by roed314** [comment]
I just replaced them all in the data.  Let's leave the search queries as is for the moment.

**Comment by AndrewVSutherland** [comment]
I also went through the seminar homepages and made sure the current versions all have valid URLs for homepages (we are now validating this but were not for a while)
