### ISSUE TITLE
Conversion of URLs to links on seminar pages

### ISSUE THREAD

**Issue by poonen** [roed314/seminars#165]
It seems that sometimes on a seminar's page, a URL in the description gets mangled with the next word before being converted to a link.

For an example, see

https://master.mathseminars.org/seminar/mitpde

**Comment by AndrewVSutherland** [comment]
I know where the problem is.

**Comment by AndrewVSutherland** [comment]
This is now fixed on master, see https://master.mathseminars.org/seminar/mitpde.
