### ISSUE TITLE
Displaying email addresses on institution pages

### ISSUE THREAD

**Issue by poonen** [roed314/seminars#166]
Are the email addresses of maintainers of institutions public on the institution's page?  If so, we should make it so that they aren't.

**Comment by AndrewVSutherland** [comment]
You are right, we should fix this.  it should link the maintainer's home page not their email.

**Comment by AndrewVSutherland** [comment]
This is now fixed on master, see

https://master.mathseminars.org/institution/BC/

for example.  We should add a check to the save institution page to make sure the maintainer's name and homepage are set (as we do for seminar organizers), and add a warning to the user profile page that they should not leave their homepage blank if they don't want their email address shown.  I'll create a separate issue for this.
