### ISSUE TITLE
Filters in searching

### ISSUE THREAD

**Issue by roed314** [roed314/seminars#169]
There was a proposal in #133 to use the "saved-favorites" filter on the search page in addition to the browse page.  We could also do the same for the other filters.  This issue is for figuring out how we want to apply filters to the seminar search results (and talk search results as well).

**Comment by poonen** [comment]
Maybe one could add a "saved-favorites" filter to the Search page, though I don't see myself using it, so I would vote no unless someone asks for it.

As for having the other filters on the Search page, this seems unnecessary given that one can already limit the subject/topic and language.

I vote to close this issue now.

**Comment by roed314** [comment]
Well, it's currently only possible to search for one topic at a time.  But I think I agree with closing this issue now; we can reopen later if desired.
