### ISSUE TITLE
Spacing on front page

### ISSUE THREAD

**Issue by poonen** [roed314/seminars#17]
On the front page, in the line above the big table, the spacing is confusing.   

1) Right now the first slider on my screen is closer to the text "Times in America/New York (now UTC -4)" than to the text "Filter by topic" that it should be associated with.  There needs to be more space to the right of "Times in America/New York (now UTC -4)".

2) Ideally the text "Times in America/New York (now UTC -4)" should be left justified with the left edge of the big table.

3) It would be nice if there were less space between each slider and the text label to its right.

**Comment by edgarcosta** [comment]
I think I have addressed this one.

**Comment by AndrewVSutherland** [comment]
Looks good.
