### ISSUE TITLE
Don't display maintainer name on institution page

### ISSUE THREAD

**Issue by poonen** [roed314/seminars#174]
On an institution page such as 
   https://mathseminars.org/institution/BC/
I find it weird that the maintainer's name is prominently displayed, especially when (as in this example) the maintainer is not associated with the institution.  On the other hand, we do want people to be able to contact the maintainer in case something needs to be fixed.

I would propose the following compromise: Instead of a line like
   "Maintainer: Bjorn Poonen"
just include a link at the very bottom of the page, not part of any paragraph of text, saying
   "Contact this page's maintainer"
and linking to the maintainer's homepage (or email address if the homepage URL is not provided) without printing the name.

**Comment by AndrewVSutherland** [comment]
@poonen I agree this would be better and it's easy to do.
