### ISSUE TITLE
Endorsing someone who has already been endorsed

### ISSUE THREAD

**Issue by poonen** [roed314/seminars#178]
The system sends you back to the top of the account page, and does include the text
"Alex M Blumenthal is already able to create content."
in the endorse section, but it would be good if the system took you to that place in the page where you were, and also displayed this temporary response in a colored rectangle to highlight it.

**Comment by AndrewVSutherland** [comment]
OK, I think issue is now addressed on master.  I did not implement exactly what you suggested, instead all informational/warning/error messages associated with endorsing users are now displayed at the top of the screen using the same shaded message box format that is used everywhere else on the site.  I think this is more consistent, and more visible to the user.

In the case where there is a "Send email" button the user can press to send a pre-endorsed user an email, this is noted in the confirmation message.
