### ISSUE TITLE
Talk not visible?

### ISSUE THREAD

**Issue by AndrewVSutherland** [roed314/seminars#181]
Why isn't this talk

https://mathseminars.org/talk/VLSDynamics/3/

visible on the seminar page

https://mathseminars.org/seminar/VLSDynamics

Is it not hidden.  It also does not show up in searches.  Marking this as critical because it is potentially serious (but maybe I am missing something).

**Comment by edgarcosta** [comment]
There was an html typo in the seminar comments
```
<p>See <a href="https://www-math.umd.edu/dynamics-conference.html>seminar web page</a> for Zoom links to individual seminars.</p>
```
that messed up the layout of everything.
I have fixed the typo.
