### ISSUE TITLE
Privacy policy

### ISSUE THREAD

**Issue by poonen** [roed314/seminars#190]
I drafted a privacy policy: see 
http://math.mit.edu/~poonen/privacy.html

Can someone create a new tab "Privacy" under "Info" linking to a new file privacy.html and then paste the contents of my file into it?  Probably you can improve the formatting too, if you want!

It would be nice also to create a tab "Policies" under "Info" linking to a new file policies.html that would contain a title "Policies" with text underneath saying "Under construction".  I will then paste in the actual text when I am finished with it.

I think the ordering of the subtabs under "Info" should be 
Features, FAQ, Policies, Privacy, Acknowledgement, Contact

**Comment by roed314** [comment]
Thanks @poonen!  I've just merged the files into master.  You can see them live [here](https://master.mathseminars.org/privacy) and edit them [here](https://github.com/roed314/seminars/edit/master/seminars/templates/privacy.html) and [here](https://github.com/roed314/seminars/edit/master/seminars/templates/policies.html).  I'm going to close this issue, but feel free to open another if there are more changes you'd like to see (or just edit the files).

**Comment by edgarcosta** [comment]
`right to the erasure of your information when it is no longer necessary for us to retain it,`

right to delete your information?

**Comment by roed314** [comment]
> `right to the erasure of your information when it is no longer necessary for us to retain it,`
> 
> right to delete your information?

Updated

**Comment by poonen** [comment]
> > `right to the erasure of your information when it is no longer necessary for us to retain it,`
> > right to delete your information?
> 
> Updated

That is simpler wording, though the GDPR Article 17 text uses the language "right to erasure", so I wonder if we should keep it!  I took much of this text from the arXiv, which itself paraphrased the GDPR instead of quoting it directly.  For now, I'll just make it "right to have your information deleted", which I think is closer to the intent (and also closer to what we would actually do if someone wants to delete more than just their account).
