### ISSUE TITLE
Policies page

### ISSUE THREAD

**Issue by poonen** [roed314/seminars#192]
We should all look at the policies (under Info) to make sure we agree with them.  Most of the items are noncontroversial, but a few may be worth discussing.

**Comment by rbommel** [comment]
For me this seems reasonable. Maybe there should be a liability waiver or something for the American users, don't know how that exactly works over there...

**Comment by AndrewVSutherland** [comment]
@rbommel We do not collect or store IP addresses.   Google analytics gives us geographic summary data, but this information is very broad and does not include IP addresses.

**Comment by poonen** [comment]
@rbommel: I added a liability statement near the bottom.

**Comment by poonen** [comment]
@rbommel: I removed "If the data is not public".

**Comment by roed314** [comment]
Do we want to advertise viXra?  We place no constraint on the location of the preprint and are just giving arXiv as an example.  I feel like mentioning viXra is likely to encourage people to post talks about papers on viXra....

**Comment by AndrewVSutherland** [comment]
I share @roed314 's concern.

**Comment by poonen** [comment]
I was thinking that this would give cranks somewhere to go instead of our site.  Anyway, I don't have a strong feeling about this.

**Comment by edgarcosta** [comment]
I have removed vixra.

**Comment by roed314** [comment]
I also think we should change "Organizers and endorsed users must use their actual full name on this site" to "Organizers and endorsed users must provide either their legal name or their chosen professional name."  I think there are two problems with the current phrasing.  First, there's the issue of what "actual" means: there are some users who might have reason to use something other than their legal name (e.g. transgender users or victims of domestic violence; see https://en.wikipedia.org/wiki/Facebook_real-name_policy_controversy).  Second, full name is also ambiguous: are we going to require @edgarcosta to include all of his names?

I'm open to other suggestions.

**Comment by edgarcosta** [comment]
What about just professional name?
And what we do with accounts that are meta accounts for seminar
organization?

**Comment by poonen** [comment]
@roed314: I implemented this.  @edgarcosta: Those are good points that should be dealt with.

**Comment by poonen** [comment]
Maybe we shouldn't allow meta accounts; i.e, only people can post.

**Comment by AndrewVSutherland** [comment]
Perhaps we should say that anonymous posting by individuals or organizations is not permitted and then say that in addition to using a professional name we require either a homepage with contact information on it or their consent to publicly post their email address (we warn them this will happen when they add organizers to a seminar without a homepage but it would probably good to mention this on the policy page).

I don't necessarily have a problem with an organization posting if there is a homepage with contact information on it (but I could also see a humans-only argument).

**Comment by AndrewVSutherland** [comment]
@poonen We added a bullet to user behavior indicating that user accounts should be associated to individuals.  If you are happy with this I think we can push this to live and close this issue.

**Comment by roed314** [comment]
Talking with @poonen now, and we can create more issues if necessary.
