### ISSUE TITLE
Seminar comments on edit talk page

### ISSUE THREAD

**Issue by poonen** [roed314/seminars#198]
When I am editing a talk, I may have forgotten what is already in the seminar comments.

Therefore I suggest: At the Edit talk page, 
1. Change the name of the Comments box to "Talk comments".
2. Immediately below it, print "Seminar comments" followed by the seminar comments displayed as an un-editable block of text.

Also, please someone check to make sure that we are not copying the seminar comments into the talk comments box as a default?  (That would not make sense anymore, now that we are printing both.)

**Comment by AndrewVSutherland** [comment]
I will take care of this.

**Comment by AndrewVSutherland** [comment]
PR #199 addresses this and should now be visible on master.

I confirmed that we are not copying seminar comments into talk comments any more.  There are many older talks with comments that duplicate seminar comments (we check for duplicates and only display once, so this will only be visible on the edit pages not the view pages).

We should take a pass through the database to remove talk comments that duplicate seminar comments (but we need to be careful to do this carefully so we don't impact any concurrent edits).
