### ISSUE TITLE
Preview of abstract doesn't break paragraphs

### ISSUE THREAD

**Issue by tornaria** [roed314/seminars#200]
Breaks *do* work in the talk page.

Steps to reproduce:

1. edit abstract for a talk
2. write some text including empty lines to indicate paragraph breaks
3. the preview shows the text as a single paragraph
4. after saving, in "view talk" we can see the paragraph breaks actually work.

**Comment by AndrewVSutherland** [comment]
Confirmed, this is a bug in how the abstract is being rendered in the preview.

**Comment by edgarcosta** [comment]
It has been resolved, and it will make it to the official website tonight
