### ISSUE TITLE
Duplicate name in public users

### ISSUE THREAD

**Issue by poonen** [roed314/seminars#202]
There are two users named Mingchen Xia
at https://mathseminars.org/user/public/

**Comment by edgarcosta** [comment]
Mingchen Xia has two accounts with two different email addresses.

The same thing for me, as you will see me there twice.

**Comment by poonen** [comment]
OK, I guess we permit this.

**Comment by AndrewVSutherland** [comment]
I think we have to permit the same name to show up with different emails (they might actually be two different people), but each user should ideally have only one account on our site, possibly with more than one email associated to it if we want to support this.  This isn't crucial right now (so should be low priority) but it may become important later.  arXiv only allows users to have one account (as a matter of policy, they don't enforce this in code).

**Comment by edgarcosta** [comment]
FYI, now that we have SU powers, I'm happy to delete my account.
