### ISSUE TITLE
Talk is listed with two equivalent timezones

### ISSUE THREAD

**Issue by poonen** [roed314/seminars#204]
See 
https://mathseminars.org/talk/STAGE/4/

The talk is listed as having two time zones.  The talk time zone should override the seminar time zone when they differ.

**Comment by AndrewVSutherland** [comment]
@poonen I don't think there is a bug here (or at least it is doing what I think it is supposed to do, whether that is what it actually should do is a separate question).

If your time zone and the talk time zone are not exactly the same it shows both (even if the times are actually the same), one labelled "your time" and one labelled "talk time"  The seminar time zone is not relevant.  You can see this yourself by changing the seminar time zone (and you can also try changing your time zone to see what happens -- if you make it the same as the talk time zone you will see just one time)

But let me know if you think it should be doing something different.  I could certainly see an argument for only displaying one time when the time zones are different but the time is the same in both time zones.

**Comment by roed314** [comment]
When I change my time zone I get
```
Wed Apr 29, 10:00-11:30 (6 days from now) in your time zone, America/New York.
Wed Apr 29, 10:00-11:30 (6 days from now) in talk time zone, US/Eastern.
```
which is kind of annoying.  But if I change my time zone to South America, I think
```
Wed Apr 29, 10:00-11:30 (6 days from now) in your time zone, America/La Paz.
Wed Apr 29, 10:00-11:30 (6 days from now) in talk time zone, US/Eastern.
```
is somewhat useful.  I don't see an easy way to distinguish these cases.

**Comment by edgarcosta** [comment]
US/Eastern is indeed a deprecated time zone and links to America/New
York, thus we could avoid the confusing in this particular case.

However, America/Detroit
<https://en.wikipedia.org/w/index.php?title=America/Detroit&action=edit&redlink=1>
!= America/New_York
<https://en.wikipedia.org/w/index.php?title=America/New_York&action=edit&redlink=1>,
even though they are isomorphic.

**Comment by poonen** [comment]
OK, I guess it's not a bug!  But still it looks weird.  

My suggestion would be simply to print only the time in your time zone, not the time in the talk time zone.  I think I need the time in the talk time zone only when I am editing a talk or seminar.

**Comment by roed314** [comment]
I'm happy with only using the viewer's time zone, especially since we're explicitly stating that it's in "your time zone."  Another possibility would be to have a toggle where the user could click to switch between their time zone and the talk's time zone.  Then we'd never be displaying both at the same time.

**Comment by poonen** [comment]
I'd recommending not including a toggle, since the point was to declutter the page.  I think the viewer's time zone should be enough here.

By the way, when on a seminar page I click a talk title, the gray box lists a time without specifying what time zone.

**Comment by AndrewVSutherland** [comment]
PR #219 removes the talk time zone from the View talk page.
