### ISSUE TITLE
Talks are present, but seminar is hidden (Nikon Kurnosov)

### ISSUE THREAD

**Issue by poonen** [roed314/seminars#21]
Nikon Kurnosov <nikon.kurnosov@gmail.com>
wrote
-----------------------------
Hey Bjorn!

Just a question -- the talks of seminar are present in a list, but seminar
itself is hidden though.

What should I change?

Best
Nikon
-----------------------------

What do I tell him?
--Bjorn

**Comment by AndrewVSutherland** [comment]
@poonen Do you know the seminar he is referring to?  My guess is its an issue with email addresses not matching.

**Comment by roed314** [comment]
I would guess that it's an email issue as well.  Currently the seminar is hidden, as is the first of the three talks.  For now, I will se the seminar and talks to display True manually, but we still need to figure out why this happened.

**Comment by edgarcosta** [comment]
I have fixed the bug, and added a message to hidden talks and seminars:
- https://mathseminars.org/talk/testseminar/1/ (https://github.com/roed314/seminars/blob/master/seminars/templates/talk.html)
- https://mathseminars.org/seminar/testseminar (https://github.com/roed314/seminars/blob/master/seminars/templates/talk.html)

Feel free to edit the wording.
