### ISSUE TITLE
Seminar name is a link to where?

### ISSUE THREAD

**Issue by poonen** [roed314/seminars#216]
When I click a seminar name like "STAGE", sometimes it takes me to the internal mathseminars.org page for the seminar, and sometimes it takes me to the external homepage.  On a talk page, both behaviors are present!  This is confusing.

I'd suggest making it always link to the internal page, and to use only "External homepage" to link to the external homepage.  This means that on the seminar page itself, the title itself would not be a link (but the external homepage link will be there, lower down on the page - perhaps it should be moved to be right under the title).

**Comment by AndrewVSutherland** [comment]
PR #219 resolves this.

**Comment by poonen** [comment]
I would fix this problem also at the edit schedule page (make the seminar name a link to the internal page).

I still think that on the seminar page itself, the seminar name should not be a link at all (behavior should be uniform), but the "External homepage" link should be moved to be immediately below it.

**Comment by AndrewVSutherland** [comment]
@poonen Sure, I can do this.

**Comment by AndrewVSutherland** [comment]
@poonen I've implemented the changes you requested which should now be up on master.  All links on the seminar name should lead to the View Seminar page and on the View seminar page the name should not have a link.  The external homepage link is available on both the View seminar pages and the Edit schedule pages, but with one difference -- on the Edit schedule page the External homepage link opens a new tab (When editing the schedule the organizer is likely to be copying information from the external home page and this is easier to do from a separate tab).

Please take a look and let me know if you think anything else needs to be done, or if not, close the issue and I will push master to live.

**Comment by poonen** [comment]
Thank you!  Also on the "View seminar" page, I'd move the "External homepage" link up, immediately below the seminar name.

**Comment by AndrewVSutherland** [comment]
Done.  There is still a bit more space than I like between the seminar name and the external link, but this is standard for an HTML h1 header.  Let me know if you want me to restyle it to tighten the spacing a bit.

**Comment by poonen** [comment]
Yes, it would be better to have space under "External homepage" rather than above it, if this is not too painful to accomplish.

**Comment by AndrewVSutherland** [comment]
@poonen Done, I think the spacing is better now.
