### ISSUE TITLE
Removing unused columns from schemas

### ISSUE THREAD

**Issue by roed314** [roed314/seminars#218]
We have a number of extraneous columns floating around that should get cleaned up (once we confirm again that they're not in use).  When we do delete them, we'll probably need to restart the webserver.

* In the `talks` table, `subject`, `visiblity`, `speakers`, `speaker_emails`, `speaker_affiliations`, `speaker_homepages`, `level`
* In the `seminars` table, `subject`, `archived`, `weekday`, `start_time`, `end_time`, `level`
* In the `seminar_organizers` table, `contact`, `subject`, `full_name`
* In the `preendorsed_users` table, `subject`
* In the `users` table, `phd`, `admin_subject`, `endorsed_subject`, `endorser_subject`
* In the `institutions` table, `aliases`
The `categories` table is no longer used.

**Comment by AndrewVSutherland** [comment]
Other schema changes I think we should make:

* In the `talks` table add a new column `stream_link` for view-only live feed (e.g. on YouTube)
* In the `seminar_organizers` table add `name` column to replace `full_name` (we use `name` everywhere else to mean full name, e.g. in the `users` table); once the code has been changed to use `name` drop the `full_name` column.

**Comment by AndrewVSutherland** [comment]
OK, we have added `stream_link` to `talks` and `name` to `seminar_organizers`.

**Comment by AndrewVSutherland** [comment]
Depending on what we decide, we may later want to drop `speakers`, `speaker_emails`, `speaker_homepages`, and `speaker_affiliations` from `talks`; just so we don't forget.

**Comment by AndrewVSutherland** [comment]
Actually I think we should keep `speakers` et al.

**Comment by AndrewVSutherland** [comment]
Done!
