### ISSUE TITLE
Schedule support for seminars with two talks per day or that meet twice a week

### ISSUE THREAD

**Issue by AndrewVSutherland** [roed314/seminars#22]
Many seminars (e.g. and https://mathseminars.org/seminar/WHSymplectic and https://mathseminars.org/seminar/LeipzigNonlinAlg) have multiple talks per day and/or meet twice a week, neither of which are easily handled by the current interface.

One solution would be to make the scheduled time for the seminar a list rather than a singleton, e.g. this seminar has a talk at 1300 each Tuesday, and also a talk at 1500 each Thursday (so the seminar has two slots that both repeat every 7 days).

**Comment by roed314** [comment]
See #32

**Comment by AndrewVSutherland** [comment]
@roed314 Thanks, but I think there is still a bit more to do on this (e.g. specifying the times of more than one talk), and I don't think it yet supports multiple talks per week (unless I missed something).

**Comment by roed314** [comment]
I added a field to the edit seminar properties for "talks per day."  There is certainly more that could be done in terms of making start time and end time lists, but I think it's at least fairly usable now, since you have two time slots per day and can edit them in the schedule.

**Comment by AndrewVSutherland** [comment]
Agreed, this is certainly lower priority than other issues, I was just noting that the issue is not fully resolved by #32.

**Comment by roed314** [comment]
I updated https://mathseminars.org/seminar/WHSymplectic and https://mathseminars.org/seminar/LeipzigNonlinAlg to have 2 and 3 talks per day respectively.  Take a look at their edit schedule pages to see what's currently there.

**Comment by AndrewVSutherland** [comment]
@roed314 Thanks.  It would obviously be nice if it could replicate the pattern of times automatically, but this is certainly usable as is.

**Comment by AndrewVSutherland** [comment]
We now have columns for start_times and end_times in the schema, we just need to add this to the UI.  Bumping the priority because i have gotten a couple of emails me about this in the last 24 hours (in both cases they are seminars with two talks)

**Comment by AndrewVSutherland** [comment]
PR #345 which is now live on master.  There are certainly further tweaks that could still be made (e.g. allowing the user to change the time slots for the series on the schedule page, or more options for periodicity, e.g. monthly), but the basic functionality is there.  You can now create seminar series that meet weekly, biweekly, triweekly with up to 12 distinct time slots --  these time slots all have to be in the same week (so you cannot, for example, create a seminar that meets every week but has a different schedule in alternating weeks, but you can create a bi-weekly event that has two lectures each time it meets, which is by far the more common use case for bi-weekly seminars).

I'm going to close this issue, but please feel free to create a new issue if you find a bug or if there are UI changes you think should be made.  It would be good to exercise this a bit on master before pushing to live -- there are a lot of underlying code changes (for example, I changed how seminar times are stored in the database, they are no longer offsets from 1/1/2020, and I uniformized a bunch of the date/time/daytime-interval code) -- in particular, whenever we use the datetime module we now do "from datetime import datetime (and whatever else we need)" and should never need to use datetime.datetime.something (this was previously done in some places but not others).
