### ISSUE TITLE
More search options

### ISSUE THREAD

**Issue by AndrewVSutherland** [roed314/seminars#23]
It would be nice to be able to search seminars by organizer/curator and by external URL.  When entering an organizer/curator you should be able to use either a name or an email address (and for names it should search for the words, not require an exact match).

<s>Similarly, it would be nice to be able to search talks by speaker.</s>

**Comment by edgarcosta** [comment]
We already have searching by speaker. Or am I missing something?

**Comment by AndrewVSutherland** [comment]
@edgarcosta Sorry, yes you can search talks by speaker, scratch that.

**Comment by AndrewVSutherland** [comment]
You should also be able to search using the seminar id (typing a seminar id into the keywords when  searching either talks or seminars should work, and you should also be able to type a seminar id into the seminar name input).

**Comment by AndrewVSutherland** [comment]
Incorporated into #201
