### ISSUE TITLE
Saving talk with no changes updates the database

### ISSUE THREAD

**Issue by AndrewVSutherland** [roed314/seminars#240]
Clicking the save button when editing a talk is now creating a new version even when no changes are made.  The code to check whether the new version matches the old version used to work but for some reason is no longer working correctly.

As I write this the behavior on master and live differ (on live only the first save incorrectly updates the database, on master every save does).  But this will no doubt change with the next push master --> live.

**Comment by AndrewVSutherland** [comment]
I'm marking this as a bug simply because the code is not doing what it is meant to do; the bug is harmless and does not impact users.

**Comment by edgarcosta** [comment]
I think we have addressed this bug.
