### ISSUE TITLE
Add future/past tabs to browse

### ISSUE THREAD

**Issue by jamiesully** [roed314/seminars#256]
It might be useful to have the main browse view be tabbed with future (default) / past tabs. 

The use case would be users coming to the site to see recently completed seminars in a topic they care about and look for recordings.

**Comment by jamiesully** [comment]
I'm interested in getting started on this enhancement (unless others would rather I didn't).

One immediate question: Should 'Recent Past' talks be done as a tab on the browse page or as a new top level page?

(Or any other strong feelings about how to do this?)

**Comment by edgarcosta** [comment]
David was just working on having a tab for conferences in the browse page.
I assume that next to it we want to show past talks.

**Comment by jamiesully** [comment]
@roed314 (When you have time), it would be great to coordinate to see what is the best way to go about this without getting in the way re building the conferences tab.

**Comment by roed314** [comment]
We're all going to a seminar at 1 our time, but maybe Zoom afterward?  See my PR for the current status.

**Comment by AndrewVSutherland** [comment]
This has been done.

**Comment by wenh06** [comment]
> This has been done.

**Comment by wenh06** [comment]
> This has been done.

I think the past talks in one's favorite talks might could also be listed in a separate tab or page, just like in the homepage (browse page).
