### ISSUE TITLE
Display topics on talk/seminar description

### ISSUE THREAD

**Issue by jamiesully** [roed314/seminars#258]
It would be useful to explicitly show users a list of the topics that have been tagged for a seminar series or individual talk.

**Comment by roed314** [comment]
Show where?  I think they're currently only shown on a seminar homepage; they should definitely also be shown on a talk homepage.  Would you also like to see them on the knowl popup?  Other places?

**Comment by jamiesully** [comment]
At the moment I don't see them displaying anywhere. 

I think some natural places for them to appear are: the seminar page, the talk page, and the talk pop-up on browse.

**Comment by roed314** [comment]
Resolved by #283 (now on master).
