### ISSUE TITLE
Improve creating seminar experience

### ISSUE THREAD

**Issue by edgarcosta** [roed314/seminars#26]
@poonen wrote this a while ago.

The main problem I see people encountering at
  https://mathseminars.org/manage/
is that they will want to type in the full name of their seminar
into the Identifier box, despite the instructions.
The easiest way to fix this would be to ask for the seminar name
and the identifier at the same time.
That is, it would be better if the top of the page looked like

----------------------------------------------------------------------

Create a seminar or conference

Seminar name: [........]

  Identifier: [........]        [[Create]]

The identifier is a short label for your seminar, used in its URL.  It should consist only of letters, numbers, hyphens, and underscores - no spaces.

----------------------------------------------------------------------

The same comment applies to the Institutions page,
for users adding an institution.

**Comment by roed314** [comment]
This should be addressed by #61, once that's merged into `live`.
