### ISSUE TITLE
Talks not in chronological order on Edit schedule page

### ISSUE THREAD

**Issue by AndrewVSutherland** [roed314/seminars#261]
If you look at https://mathseminars.org/edit/schedule/?shortname=TheTest you will see that the two talks on April 29 are out of order on the schedule, even though they are shown in the correct order on the view seminar page.

To reproduce create two talks on the same day in chronological order, then change the times to reverse the order.

**Comment by roed314** [comment]
Fixed on master.

**Comment by AndrewVSutherland** [comment]
@roed314 Great, I'll respond to the user who reported this once we push to live.
