### ISSUE TITLE
Proposal for filter behavior on Browse page

### ISSUE THREAD

**Issue by poonen** [roed314/seminars#267]
(This came out of a discussion with Drew and Edgar (and David for part of the time).)

When someone visits the site for the first time,
no subjects are selected, no topics are selected,
and no languages are selected,
but none of the filter toggles are set,
so all talks are being displayed.

Clicking on the word "topics" opens the topic menu AND sets the toggle.
This means that for the moment, all the talks disappear,
but the opening of the topic menu is a cue to the user
to select some topics, and each time a topic is selected,
the talks from that subject populate the displayed list.

Whenever a user sets the toggle for filtering topics,
if the list of selected topics (within the subjects currently being displayed) is currently empty 
(as it will be if this is the first thing the user does upon visiting the site),
then the topic menu automatically opens,
which again is a cue that the user should select some topics.

In all cases, if the toggle is set and no topics have been selected yet,
then no talks are displayed.

Clicking the word "topics" when the topic menu is open closes the menu.
Un-setting the toggle does not close the topic menu.

The other toggles and the word labels "subject" and "language"
would work in the analogous way.

Some advantages of this are that
1) there is no need to ask the user to select subjects and click done
   when they first visit the site;
2) the user starts by seeing everything;
3) whether they first click on the word "topics" or the toggle,
   they will immediately see the effect of the filter
   and see the topic menu so that they can add what they want;
4) the behavior is uniform (and I think logical).

**Comment by roed314** [comment]
I've implemented this in #270.  I'm not going to merge it tonight since I'm about to sleep, but if it looks good @AndrewVSutherland  or @edgarcosta can merge it in the morning (I tested it some, but it should probably be tested after clearing cookies).
