### ISSUE TITLE
Port cookies from mathseminars.org to researchseminars.org

### ISSUE THREAD

**Issue by roed314** [roed314/seminars#271]
I realized tonight that my mechanism for porting cookies during a redirect from mathseminars.org to researchseminars.org won't work, since they'll be on a different domain.  We should try to come up with a good way of doing this so that users topic and language filters aren't erased.

**Comment by AndrewVSutherland** [comment]
@roed314 I believe we came to the conclusion after yesterday's discussions that it would be better to simply not port the cookies.  Having users initially see all subjects (and a notation indicating that they currently have no filters set) will both make them aware of the new content that is available and familiarize them with the new subject/topic selection interface.

Anyone who uses multiple devices or browsers or occasionally clears cookies from their browser is already going to be familiar with the fact that they occasionally need to repeat actions that set cookies, so I don't think this puts an undo burden on our users.

And of course it makes our lives a lot easier :).  But this will give us time to work on other high priority issues that I think have a greater impact on users.
