### ISSUE TITLE
Feature request: show me which talks are new since my last visit

### ISSUE THREAD

**Issue by rbommel** [roed314/seminars#272]
Now I have been using MathSeminars for quite a while, but the number of talks in my interest area is slowly getting out of control. Every time I come to check if there are some other interesting things I want to see, I have to browse through a very long list.

Therefore, I have the following feature request: I'd like to somehow see which talks are new (or modified maybe) since I last visited the website. This would require a time stamp to be stored for each talk when it is created (or updated), and a time stamp of my last visit (maybe even with the possibility to change this time stamp on the user side).

Of course there is the question of how new talks should be displayed. There are several options (could even be configurable, but maybe that's too much, or maybe just togglable):
- make new talks bold
- grey out old talks slightly
- put a star or something in front of new talks

I am curious to know how others think about this idea. For me, it would improve the usability of the site by a lot.

**Comment by roed314** [comment]
I like this idea.  Another possible interface possibility would be to have another filter for talks that have been added/updated since the last visit.

**Comment by poonen** [comment]
This issue is solved by what is on the test branch.
