### ISSUE TITLE
Add knowl to "Filter by" in browse page

### ISSUE THREAD

**Issue by edgarcosta** [roed314/seminars#274]

**Comment by poonen** [comment]
I think I succeeded in adding this knowl to master, but I have a few questions:

1) Why do the filters themselves shift right when this knowl is opened?

2) Can the underlines inside the knowl be made dotted underlines, to look like the words they are referring to?

3) Can we <i>right</i> justify the last sentence of the knowl?  I want to distinguish it from the main text of the knowl.

4) How can we visually distinguish this knowl from the filter words (subject, topic, language,...)?  I think this is important.  Can we make the filter words green, say?  If so, can we make the toggles green too?
