### ISSUE TITLE
Search page does not list series with talks happening now first

### ISSUE THREAD

**Issue by poonen** [roed314/seminars#289]
On the Search page, series are ordered by next talk.  These should start with series that have a talk happening right now.

**Comment by roed314** [comment]
I can do this.  I'm curious what your "invalid" label indicates though.  I think the standard meaning when applied to issues is that "this is not actually a problem with the software and should be closed."

**Comment by poonen** [comment]
The description of the "invalid" tag says "This doesn't seem right".
I am saying that the current behavior of the site doesn't seem right.

At first I used "bug", but I wasn't sure if "bug" was the correct label, because perhaps the site was behaving exactly as you had intended even though I thought it should behave differently!

**Comment by poonen** [comment]
I edited the descriptive text of the "invalid" tag, to conform with your interpretation of it.
