### ISSUE TITLE
Time zones on the "Edit schedule" page

### ISSUE THREAD

**Issue by poonen** [roed314/seminars#29]
If a talk's time zone differs from its seminar's time zone, then the talk is listed on the seminar's "Edit schedule" page in the talk's time zone, contrary to what the page claims it is displaying.
For an example, see 
https://mathseminars.org/edit/schedule/?shortname=testseminar

**Comment by roed314** [comment]
See #32

**Comment by edgarcosta** [comment]
I believe this is fixed
