### ISSUE TITLE
Headers

### ISSUE THREAD

**Issue by poonen** [roed314/seminars#290]
Bug: The search page says "Search series" even when one is searching for talks.

On the Create/Manage page, the subtab "Seminars" should be "Series".

On the FAQ page, can we change the header to "Frequently asked questions" (but leave the tab the same)?

On the Contact page, make the header "Contact and feedback" to conform with capitalization elsewhere, or just make it "Contact".

**Comment by edgarcosta** [comment]
I have addressed all these issues.
