### ISSUE TITLE
Searching talk abstracts by keyword

### ISSUE THREAD

**Issue by poonen** [roed314/seminars#30]
The "Info" page claims that one can search talk abstracts by keyword, but this is not working.  For example, I searched for "variance" and got nothing, despite the word appearing in the abstract of 
https://mathseminars.org/talk/agstanford/5/

**Comment by MaxAVF** [comment]
I think the search by keyword is working as stated. Note that search "by keyword" means searching the list of keywords assigned to every talk, not actually searching over the words apppearing in the abstract. In that example, "variance" is not a keyword of that talk. Maybe that's another feature that could be addded.

**Comment by poonen** [comment]
@MaxAVF: I don't know what you are talking about.  There is no option on the "Edit talk" page to associate keywords to a talk.  There is no option on the "Edit seminar" page to associate keywords to a seminar.  Meanwhile, the "Info" page says "You can search for seminars and talks satisfying various criteria, including specifying keywords within talk abstracts".  Is there supposed to be some way of designating some words in a talk abstract as being keywords?  I had interpreted the sentence on the "Info" page as saying that searching by keyword would search the full text of every abstract.

**Comment by AndrewVSutherland** [comment]
@MaxAVF Actually talks do not have assigned keywords.  They did once, but we concluded that it was unreasonable to expect people to add keywords and in a situation where most are not adding keywords it was more useful to just search the abstract.

**Comment by MaxAVF** [comment]
My bad, i just tried searching for the keyword "group" and found this talk that has a list of keywords below the abstract https://mathseminars.org/talk/TopologicalGroups/1/
So I assumed every talk had the option to add keywords, and the search was actually looking at those keywords, but seems like it's not.

**Comment by AndrewVSutherland** [comment]
@poonen, Your interpretation is correct, the intent is that this search should check for any of your keywords appearing anywhere in the abstract (case insensitvely) and return all talks that match.  The fact that it is not doing this right now is indeed a bug.

If a speaker or organizer wants to add keywords to an abstract (that don't already appear in it), they can just add a line to the bottom of the abstract (e.g. "Keywords: foo, bar") and the search will find them just as they would any word in the abstract (once this bug is fixed).

**Comment by AndrewVSutherland** [comment]
@MaxAVF Yeah, I can see why you were confused, that is simply the comment field for the seminar (see see https://mathseminars.org/seminar/TopologicalGroups), which the organizers chose to make a list of terms (and the seminar keyword search should find them).

**Comment by poonen** [comment]
I made this "high priority" because this is something that probably a lot of users, registered or not, are encountering.

**Comment by roed314** [comment]
This was also resolved by #49.
