### ISSUE TITLE
More headers

### ISSUE THREAD

**Issue by poonen** [roed314/seminars#300]
"Edit seminar properties" needs to be "Edit series properties".
"View seminar" tab needs to be "View series".

**Comment by AndrewVSutherland** [comment]
This is now fixed on master.

**Comment by AndrewVSutherland** [comment]
whoops missed one

**Comment by AndrewVSutherland** [comment]
Sorry for the confusion, we were previously showing

"Edit conference properties" or "Edit seminar properties"

but always showing "View seminar" (never "View conference") which was inconsistent (independent of the switch from seminar to seminar series.

I have changed it so it is now always "Edit series" and "View series", whether is is a conference or not.

We could replace series with "conference" or "seminar series" depending on context; let me know if this is what you want.

**Comment by poonen** [comment]
Your solution is simplest.  In fact, I think that in general it makes sense to downplay the difference between conference and seminar series.
