### ISSUE TITLE
New seminars on mathseminars.org are not visible in browse or search

### ISSUE THREAD

**Issue by AndrewVSutherland** [roed314/seminars#305]
As of yesterday, if you create a new seminar on mathseminars.org by default it will be saved with subjects set to the empty list, which means that it will not be visible on mathseminars.org, nor will any of the talks in it (it will be visible on researchseminars.org).

This is a serious bug.

**Comment by AndrewVSutherland** [comment]
There are several recently created math seminars impacted by this, including https://mathseminars.org/seminar/AppliedAlgebra

**Comment by edgarcosta** [comment]
This is the list of shortnames of seminars with no subject (I will
start adding subjects from the top):
{'AnalysisUR',
 'AppliedAlgebra',
 'BHIColloq',
 'Holography_AdSCFT',
 'MC-NITOC',
 'SC3',
 'SCGP_Physics',
 'Test123',
 'Test456',
 'TheTest',
 'moduli'}

**Comment by AndrewVSutherland** [comment]
I think it also impacts talks.  But I don't understand why 

https://researchseminars.org/talk/AppliedAlgebra/8/

does not appear on mathseminars.org (but does on researchseminars.org) I already set subjects=['math'] for every record associated to this talk and to the semianr AppliedAlgebra.

**Comment by AndrewVSutherland** [comment]
Hmm, the talk https://researchseminars.org/talk/AppliedAlgebra/8/ is visible now, maybe just a caching issue.  The fix on master seems to work -- whenever a seminar or talk is created or edited on mathseminars.org if it has not subjects set it will be set to ['math']  I'm going to push to live.

**Comment by AndrewVSutherland** [comment]
OK, the code fix is now on live and I just verified that newly created seminars and talks with no topic/subject set are visible.

@edgarcosta I think you can close this once you are satisfied all the data updates have been made.
