### ISSUE TITLE
ORCID, MR Author ID, etc.

### ISSUE THREAD

**Issue by poonen** [roed314/seminars#312]
We are now planning to allow users to add not only ORCID, but other IDs that may be subject-specific, such as the MR Author ID in mathematics.

Here is a proposed user interface specification:

On the "Account" page, just above the "Update details" button, there will be a (not directly editable) table containing something like [ignore the periods]
...... IDs: MR Author 256256
...............ORCID 100-100-100
(containing the IDs added so far, in alphabetical order, with nothing to the right of IDs if there are no IDs yet; each ID so far should have a circle X to its right which deletes that ID),
followed by an indented line
...............[dropdown menu] [input box]
where the blue-background dropdown menu displays the text "add ID (select type)"
to begin with, but with options such as ORCID, MR Author, etc. below it,  
and then the user can enter the appropriate ID number (or text) into the input box.
When "Update details" is pressed, if the dropdown menu has an entry and the input box
is nonempty, a new string like "MR Author 256256" will be added to a table in the database,
and it will be displayed in the IDs table, and the dropdown menu and input box will revert to 
their initial states in case the user wants to add another ID.
If no type has been selected but there is text in the input box when "Update details" is pressed,
a warning "ID type must be chosen; no ID was added." is flashed and no ID is added.
If a type has been selected but there is no text in the input box when "Update details" is pressed,
a warning "ID number or text must be nonempty; no ID was added." is flashed and no ID is added.

"IDs" will be a knowl explaining how this works.

Even if we do not use these IDs for anything yet, it will be easier if we start asking for them now, so that we don't have a large collection of users who registered without entering them.

**Comment by poonen** [comment]
The knowl "ids" has already been created in knowls.yaml  
It is just waiting for someone to implement the functionality.

**Comment by poonen** [comment]
I'm making this High Priority since the AMS requested this.

**Comment by AndrewVSutherland** [comment]
@poonen Please take a look at the implementation on master.mathseminars.org, which is a bit different than what you proposed.

I found that having to click update details for each ID was really awkward, especially when handling input validation errors.  It's also a bit confusing to have to reenter an ID into a different textbox when all you want to do is edit an ID that is already displayed on the screen -- the approach I took avoids that.

I added regex validation and a test url on the client side, which makes it a lot easier to get everything right the first time, and you can add multiple ids at once. 

I took the liberty of adding your MR number so you can see what it looks like, but you can remove it by making it blank and r, but you can try adding your arXiv, zbMATH, and ORCID id's (and of course you can remove your MR number and add it again).

All the information about external  ids is stored in the database, including the caption, placeholder, regular expression, format, and test URL format, so we can easily tweak these and add more without making any changes to the code.

**Comment by poonen** [comment]
@AndrewVSutherland It looks good!  The only thing I'd suggest is that you put the types in alphabetical order in the dropdown menu.

**Comment by AndrewVSutherland** [comment]
@poonen I fixed the sort (it was sorting case sensitively before).  I'm going to push this to live now.
