### ISSUE TITLE
Knowl for unsaved talk on browse page 

### ISSUE THREAD

**Issue by poonen** [roed314/seminars#317]
On the Browse page, if I open the knowl for an unsaved talk (i.e., not a favorited talk), and then set the filter to show only saved talks, the talk row disappears, but the knowl remains with no way to close it (other than unsetting the filter).  

I think that what should happen is that the knowl should remain open but hidden, redisplayed if the filter is unset.

**Comment by AndrewVSutherland** [comment]
Also, if you favorite a talk, show only favorites, and then unfavorite the talk, the talk is still shown (but you cannot open the knowl).

**Comment by poonen** [comment]
I think somebody fixed this but forgot to close the issue, so I'm closing it now.
