### ISSUE TITLE
Put create series below existing series on Manage page?

### ISSUE THREAD

**Issue by AndrewVSutherland** [roed314/seminars#322]
One user has suggested that we should put the Create series section of the Manage page below the list of existing series the user is managing, arguing that managing existing series is a much more common reason to go to this page than creating a new one.  For users who have not yet created any series, the page would still look the same.

My main worry about this is that once a user has create a lot of series the create option will scroll off the bottom.  So my personal inclination would be to not do this, but I'm creating an issue to let others weight in.

**Comment by edgarcosta** [comment]
> My main worry about this is that once a user has create a lot of series the create option will scroll off the bottom. 

However, at that point, he also knows where to go, and most of our users will manage only a couple of seminars.

**Comment by poonen** [comment]
I think that putting the Create series below the existing series makes sense, though I do not have a strong feeling about it.

**Comment by roed314** [comment]
Resolved on master.

**Comment by poonen** [comment]
Nitpick: It's a little weird that there is more vertical white space below "Create new series" than above it.  "Create new series" should logically be more closely tied to the material below it.

Anyway, feel free to close this issue again.

**Comment by poonen** [comment]
I fixed the spacing, I think.
