### ISSUE TITLE
Access to talk knowl on Edit talk page

### ISSUE THREAD

**Issue by AndrewVSutherland** [roed314/seminars#324]
It would be nice to have  a link that lets you preview the talk knowl while on the Edit talk page, perhaps linked to the word "talk" at the top, or to the title of the talk.

Also, should the talk title appear in the talk knowl?

**Comment by edgarcosta** [comment]
#297 addresses your last comment

**Comment by AndrewVSutherland** [comment]
@edgarcosta Yeah but #297 still has a big red button in it :)

We should also add talk knowl links on the edit schedule page (maybe next the details link).  When you are making updates to a seminar often you are just adding titles and abstracts that were TBA and the only thing you really want to know is whether the abstract is already present or not -- it would be nice to be able to do this without leaving the Edit schedule page.

**Comment by edgarcosta** [comment]
Yes, #297 needs some touch ups, but just saying that we already got a better knowl on its way :)

**Comment by AndrewVSutherland** [comment]
On further reflection I'm going to close this -- doing this properly would be a lot of work (we need to be able to update the knowl and preview it) with not a lot of payoff.
