### ISSUE TITLE
Keep input data if given an error when creating a series

### ISSUE THREAD

**Issue by edgarcosta** [roed314/seminars#325]
At the moment, if one tries to create a series and it triggers some error, like no subject or invalid shortname, the user loses all of its input data.

**Comment by AndrewVSutherland** [comment]
We should handle input errors here as we do in the edit talk/seminar/institution pages using show_input_errors (which takes them to inputerror.html where error messages appear along with a message telling them to press the back button and correct the errors).

**Comment by edgarcosta** [comment]
Yes, that sounds good.
I have incorporated those changes in a new upcoming PR.
