### ISSUE TITLE
Endorsement email match should probably be case insensitive

### ISSUE THREAD

**Issue by AndrewVSutherland** [roed314/seminars#34]
Currently it appears that endorsements are doing a case-sensitive check on e-mail addresses, which has caused problems for at leas one user.  The domain in name@domain is explicitly not case sensitive (but our check is treating it as such), so this is a bug.  Technically the name in name@domain is case sensitive, but almost all e-mail systems treat them as case insensitive and will not let you create distinct email addresses that differ only in case.

I suggest we should do a case insensitive comparison, or if this is deemed risky, at least do this for domains where we know it is safe (e.g. gmail.com).

**Comment by edgarcosta** [comment]
Should we force every email to be lower case?

**Comment by edgarcosta** [comment]
Here is what we need to do:
-  Store emails with case sensitivity
- Send emails with case sensitivity
- Perform internal searches with case insensitivity

**Comment by edgarcosta** [comment]
I have momentarily fixed this for endorsement
https://github.com/roed314/seminars/commit/2a673fe6c2201042e4f1b884ffa3cbe51c9f3221

I still need to implement what I said above, perhaps tonight.

**Comment by edgarcosta** [comment]
I would address the remaining issues tonight.
