### ISSUE TITLE
Browse page showing unfiltered then filtered

### ISSUE THREAD

**Issue by AndrewVSutherland** [roed314/seminars#346]
Currently if you have filtering when you go to the main browse page it briefly shows you everything then applies the filters.  This is distracting and surely slows things down (why are we even pulling all the future talks out of the database?)

**Comment by poonen** [comment]
I see this too.

**Comment by roed314** [comment]
This is how the filtering mechanism works.  What do you want to happen?  Have everything hidden and then shown instead?

**Comment by roed314** [comment]
As for why we're pulling everything out of the database, we need to in order for all the filtering to be able to work dynamically.  We've discussed limiting the talks by how far in the future they are and/or fetching talks progressively as the page loads, but neither of those has been implemented.

**Comment by AndrewVSutherland** [comment]
If the filters are on we should keep things hidden until after filtering -- if this avoids rendering calls (e.g. to katex) it will speed things up and the visual appearance will be smoother.

But I think we are going to want to eventually change the mechanism to force a refresh when filters are changed (maybe just do this for subject changes).

**Comment by roed314** [comment]
I like the idea of forcing a refresh on subject changes (eventually).  Maybe if no subjects are set we can limit the amount of time, and then if subjects are set we can just show those subjects.

**Comment by edgarcosta** [comment]
I believe we just need to edit:
https://github.com/roed314/seminars/blob/master/seminars/templates/browse.html#L51
to add some `style="display: none;"` to the talks that would be filtered out at the end of the load.

**Comment by edgarcosta** [comment]
I will try to do what I suggested.
