### ISSUE TITLE
Declutter talk knowls

### ISSUE THREAD

**Issue by poonen** [roed314/seminars#355]
In each talk knowl:

1) We could remove the word "Abstract" since in essentially all cases, it is obvious that the abstract is the abstract.

2) I think we could simplify
       Talk content
           * paper
           * slides
           * video
to
      (paper | slides | video)
which simplifies further to
      (slides | video)
      (slides)
or nothing at all, depending on how many items are present.
Or if we really want to keep the words "Talk content", at least put everything on one line:
     Talk content: (paper | slides | video)

3) It is a little ridiculous having the sentence "Some calendar services sync external calendars only every ~24 hours." on every single talk knowl.  Can we just delete it?  Or if you feel that a warning is necessary on every talk knowl, can we simplify it to a single link
       (sync delay info)
appearing to the right of the text
       ICS file
?

4) I note that the talk knowl on the Browse page is much wider than the talk knowl on the Search page.  I prefer the wider one.  
   If it is wide enough, one could even imagine having
"Export..."  and "Mon May 4, 07:30-08:30 (starts in 13 hours)"
on the same line.  But maybe this wouldn't be good on phones.

**Comment by AndrewVSutherland** [comment]
I believe all but 4 have now been addressed on master.

**Comment by AndrewVSutherland** [comment]
It looks like 4 is a function of the context and the width of the table, which we probably don't want to change, so I'm going to close this now.
