### ISSUE TITLE
Fixing typo in institution ID

### ISSUE THREAD

**Issue by poonen** [roed314/seminars#356]
Is there some way that administrators can correct obvious typos in an institution ID (and notify the maintainer), or is this too painful to be worth the trouble?  I am looking at the ID "CollegeBridhe" that someone created for "College Bridge".

**Comment by AndrewVSutherland** [comment]
This institution had not yet been associated to any series so I went ahead and just changed the identifier to the obviously intended CollegeBridge.  This shouldn't impact anything.

In general changing the institution id is something we don't really want to allow, but for mistakes caught early it's easy enough to fix manually.

**Comment by poonen** [comment]
There's now a new typo in the ID: ColledgeBridge.

**Comment by poonen** [comment]
Once this is fixed, let me know, and I can notify the maintainer, since I know him.

**Comment by AndrewVSutherland** [comment]
Oh dear, sorry about that!  Fixed!

**Comment by poonen** [comment]
I wrote to the maintainer (Edray Goins).
