### ISSUE TITLE
Server error saving changes to talk

### ISSUE THREAD

**Issue by AndrewVSutherland** [roed314/seminars#36]
Attempting to add speaker home page while editing talk leads to the following server error:

The page you are looking for has produced a server error.
To help us improve the website, please report this page's URL "http://mathseminars.org/save/talk/" as well as the URL of the page you are coming from "https://mathseminars.org/edit/talk/?seminar_id=TaoCollatz&seminar_ctr=0".

**Comment by AndrewVSutherland** [comment]
Another example of the same problem:

The page you are looking for has produced a server error.
To help us improve the website, please report this page's URL "http://mathseminars.org/save/talk/" as well as the URL of the page you are coming from "https://mathseminars.org/edit/talk/?seminar_id=IASAnalysis&seminar_ctr=0".
jump back

**Comment by AndrewVSutherland** [comment]
I think this bug only affects the talks that were uploaded from Jaume's spreadsheet.

**Comment by edgarcosta** [comment]
I'm looking intot his one.

**Comment by edgarcosta** [comment]
Is a data issue, we decided that seminar_ctr was a positive, but when
importing the data we started from 0.

**Comment by edgarcosta** [comment]
Fixed
