### ISSUE TITLE
Add language property to seminars and talks

### ISSUE THREAD

**Issue by AndrewVSutherland** [roed314/seminars#37]
It would nice for users to know which language talks are being given in.  There should be a language property for each seminar (default to english) that is used as the default for each talk in the seminar with the ability to change the language for specific talks.  You should be able to search talks and seminars by language.

We already have talks in Russian, French, and Catalan listed on the site, and I'm sure many more will follow.

A dropdown for language would be ideal (to avoid variant spellings) -- this means we will need to be prepared to add new languages as required, but my guess is the total number will be manageable (my guess is 10 or 20 languages would cover 99.9 percent of the talks).

**Comment by edgarcosta** [comment]
https://pypi.org/project/iso639/

**Comment by roed314** [comment]
I will work on this: it is also a feature I thought about earlier this week.

**Comment by roed314** [comment]
I think this is resolved by #48 and is now live.  Take a look, and update the talks that you know aren't English (I was only able to find one past Russian talk, and no Catalan talks, so the filter-by-language feature on the browse page isn't very useful at the moment).
