### ISSUE TITLE
Unable to create seminars

### ISSUE THREAD

**Issue by AndrewVSutherland** [roed314/seminars#38]
I am currently getting a server error if I try to create a seminar,. the flask log shows four occurrences of
the error

"ValueError: Need to update seminar code to account for schema change"

to reproduce go to https://mathseminars.org/manage/ and enter any seminar id that does not already exist.

**Comment by AndrewVSutherland** [comment]
@edgarcosta @roed314 Will PR #32 this, or is it something else?

**Comment by edgarcosta** [comment]
Looking into it

**Comment by edgarcosta** [comment]
Fixed.

**Comment by AndrewVSutherland** [comment]
Thanks!

**Comment by edgarcosta** [comment]
I also added a wraper around adding columns and dropping columns, that makes you think twice
```
Are you REALLY sure you want to do call <bound method PostgresTable.add_column of Interface to Postgres table categories>?
You will most likely break the website if you don't change the code first!! (yes/no)
```
