### ISSUE TITLE
Warn about google calendar issues in the FAQ

### ISSUE THREAD

**Issue by AndrewVSutherland** [roed314/seminars#39]
Edgar Costa wrote:

We should add a warning and this to the FAQ.

This is a long-standing issue that Google doesn't have a supported API method  to add calendars: https://issuetracker.google.com/issues/36753322
And the current one has bugs like what you noticed and also doesn't support https
https://stackoverflow.com/questions/12563178/link-to-add-ics-to-google-calendar-stopped-working
https://stackoverflow.com/questions/56434749/how-do-you-import-ics-file-from-an-https-link-to-google-calendar-using-a-url

**Comment by poonen** [comment]
Oops, sorry, I didn't mean to close this.  I'm not sure I understand the technical details, but if someone can explain them, I can add this.

**Comment by edgarcosta** [comment]
Here is a stub:
Q: I have exported my favorites to a calendar, but it shows no events. How can I fix that?
A: Some calendar services sync external calendars only every 24 hours. Furthermore, some service providers may take even longer for the initial sync.
If that is your case, we suggest that you re-add to the calendar by copying the URL of `ICS file` and manually adding it to your account.

**Comment by alreadydone** [comment]
This is another thing to note, specific to Google Calendar:
https://support.google.com/calendar/thread/725096?hl=en&msgid=10889694

> Google says the limit is 1MB (https://support.google.com/calendar/answer/45654?hl=en)... I usually split into 1.8MB files without problems, but according to this post the actual limit is 1,111 events: https://support.google.com/calendar/thread/1723215?hl=en

My current ICS file downloaded from researchseminars.org is 2.1MB. Directly using my link https://calendar.google.com/calendar/render?cid=http%3A%2F%2Fresearchseminars.org%2Fuser%2Fics%2FIjI0NSI.LjXVFmFMHiF502lVmYYHn4qsSOw to create a new calendar in Google will result in the loss of many events. For example, 12 out of 58 events today will be lost, and 9 out of 34 tomorrow will be lost. Importing the downloaded ICS file to Google works fine (apparently all events show up). I notice that all earlier events (prior to today) also seem to be present in the ICS file. Probably they are also are present when Google tries to sync with the link. Can you reduce the size by removing earlier events, say more than one week ago? And if necessary, only sync events within one week from today? In my use case, the calendar synced from researchseminars.org is merely for tracking things, and I'll manually copy those seminars I am interested in and actually plan to attend to my main calendar every night, so syncing 1-2 days each time would be sufficient to me.

Thanks for your attention!
