### ISSUE TITLE
Consider adding a license.

### ISSUE THREAD

**Issue by akhmerov** [roed314/seminars#4]
Hi! You've made a really nice tool! 

I'm involved in https://github.com/virtualscienceforum/virtualscienceforum, and I was wondering whether you consider allowing your code to be reused. Adding a license would help clarify this.

**Comment by roed314** [comment]
We will do so today under a standard open source license.  Do you have constraints on what you could use?

**Comment by akhmerov** [comment]
Nope, anything is good as long as it's not extremely exotic.

**Comment by AndrewVSutherland** [comment]
We have added a GPL 2.0 license (or later).
