### ISSUE TITLE
latex no longer rendering in talk knowls

### ISSUE THREAD

**Issue by AndrewVSutherland** [roed314/seminars#401]
It appears that latex in talk abstracts is no longer being rendered in talk knowls (presumably this is a result of some of the recent changes we made to speed up the browse page).

**Comment by AndrewVSutherland** [comment]
For an example, click on the title of the first talk on:

https://researchseminars.org/seminar/VSAMRT

**Comment by edgarcosta** [comment]
I pushed the fix to live
