### ISSUE TITLE
Edit seminar schedule

### ISSUE THREAD

**Issue by poonen** [roed314/seminars#414]
Right now there are headers
"Edit conference schedule"
and 
"Edit seminar schedule".

The latter should be changed to "Edit series schedule".
(We don't call a _seminar series_ a seminar anymore.)

**Comment by AndrewVSutherland** [comment]
I think it would make more sense to just say "Edit schedule" (or "Edit series schedule") in both cases.

We currently say "Edit series" in both cases when "Edit properties" is chosen.  I would argue for changing "Edit properties" to "Edit series" and having the header in the banner match the submenu header in every case.

**Comment by poonen** [comment]
@AndrewVSutherland: That sounds good to me.
