### ISSUE TITLE
Instructions when "Livestream link" varies from talk to talk

### ISSUE THREAD

**Issue by poonen** [roed314/seminars#417]
On the "Edit series" page, the instructions to the right of "Livestream link" currently say

> If link varies, enter "See comments" and put instructions in Comments.

Shouldn't we instead instruct organizers to enter the livestream link on each "Edit talk" page?

**Comment by AndrewVSutherland** [comment]
There are several reasons the link might vary, only some of which involve adding the link to each talk page (e.g. the link might be emailed to registered users the day before, in which case there is nothing to update on the talk pages).

The issue #327 has already been created to address this issue.  I'll add a comment there saying what I think should happen in the situation where there is a varying link for each talk that is meant to be posted by the organizer on the talk page.
