### ISSUE TITLE
knowl-free path to talk pages for robots

### ISSUE THREAD

**Issue by AndrewVSutherland** [roed314/seminars#42]
Currently Google is not indexing our talk pages because they cannot be reached from the front page without opening a knowl.  We should arrange the site so that a robot can find a path from the front page to every talk page without opening any knowls.

**Comment by alexjbest** [comment]
How about just linking the date + time in the leftmost column to the talk page?

**Comment by edgarcosta** [comment]
We now have a hidden column.
`wget` seems to be happy with that solution.

**Comment by edgarcosta** [comment]
I have asked for a recrawl.
