### ISSUE TITLE
Search page: layout of criteria

### ISSUE THREAD

**Issue by poonen** [roed314/seminars#421]
All the tabs on the Search page have Subject, Topic, Institution, Language, and Access.
It may be nice to put these in the same place on each tab, say always on the left side as they currently are on the Talks tab, even if this means that the other tabs will be lopsided.

**Comment by poonen** [comment]
This is related to #419.

**Comment by AndrewVSutherland** [comment]
I like this suggestion, especially since I can imagine adding some of the talk search options (e.g. speaker, institution, and especially date range) to the other search pages.
