### ISSUE TITLE
Update the feedback form

### ISSUE THREAD

**Issue by poonen** [roed314/seminars#422]
The Google Form still says mathseminars.org

**Comment by AndrewVSutherland** [comment]
I changed the form heading to "Feedback" and mention both mathseminars.org and researchseminars.org.  Once the sites are merged (i.e. mathseminars.org starts redirecting to researchseminars.org).  We may want to eventually remove the reference to mathseminars.org, but probably not for a while (even after we start redirecting, many users may still think of the site as "mathseminars.org" especially if they reach us by typing mathseminars.org into the URL bar of their browser or clicking on a link that says mathseminars.org).
