### ISSUE TITLE
Series type

### ISSUE THREAD

**Issue by edgarcosta** [roed314/seminars#433]
When looking at a series, we don't give any indication if it is a conference or a seminar series.

**Comment by AndrewVSutherland** [comment]
@edgarcosta Are you satisfied that #435 addresses is this or do you think more should be done?

Seminar series now have a line that says "Serminar times:" while conferences have a line that says "Conference dates:"

**Comment by edgarcosta** [comment]
It looks better, at least now I know what to look for.
