### ISSUE TITLE
Talk comments on view talk page

### ISSUE THREAD

**Issue by poonen** [roed314/seminars#437]
On a view talk page, it is essential that the talk comments be preceded by 
**Comments:**
in order to distinguish them from the abstract.

**Comment by AndrewVSutherland** [comment]
@poonen, that should already be the case, where are you not seeing **Comments:** before the comments?

**Comment by poonen** [comment]
Never mind, some organizer just typed in the talk comments at the bottom of the abstract field.  I'm closing this.
