### ISSUE TITLE
ModuleNotFoundError: No module named 'sage.all'

### ISSUE THREAD

**Issue by proxiex** [roed314/seminars#442]
I can't' seem to get the project running on my local machine. I keep getting the error 
` from sage.all import Integer, RealNumber ModuleNotFoundError: No module named 'sage.all'`
I am not sure why. I have tried installing sagemath module but I still get the same error.

**Comment by roed314** [comment]
Hi @proxiex,
How did you try installing sagemath?  And have you tried using @jamiesully's fork of the LMFDB, which should obviate the need to use sagemath?

Really, the answer is that we need to reduce our dependencies (see #116), but that's not a solution for you at the moment.  Also, if you'd like to help develop the project you'll need access to the development database.  Send us an email at mathseminars-dev@googlegroups.com with an introduction and what you'd like to work on and we can help.

**Comment by proxiex** [comment]
Hi @roed314,

Thank you so much, using @jamiesully version of LMFDB helped, though now I am getting a users_counts error
`psycopg2.errors.UndefinedTable: relation "users_counts" does not exist`
`LINE 1: SELECT count FROM "users_counts" WHERE cols = '[]' AND value...` I believe the `users_counts` table is missing from the `devmirror.lmfdb.xyz` database.

**Comment by roed314** [comment]
Thanks.  We need to fix the development database and figure out how to keep it's schema up to date (some of us are developing using the live database).  We'll try to get this straightened out in the next few days.

**Comment by proxiex** [comment]
Hi @roed314, 
sorry to bug but is there any update regarding the `user_counts` table missing? 
also, I tried to run the app using my local DB but kept getting
`psycopg2.errors.UndefinedTable: relation "meta_tables" does not exist
LINE 1: ...as_extras, stats_valid, total, include_nones FROM meta_table...` error.

**Comment by jamiesully** [comment]
Hi @proxiex 
The others can correct me if I'm wrong, but if you created a local DB according to the schema listed in the 'seminars' repository, than you will be missing a lot of tables. Some of these would be created automatically by the DB functions within LMFDB, should you use those to create a new table. I believe you also had to create the 'meta_tables' table independently, though. I eventually got it all to work by trial and error, but it was a chore.

Based on my experience going through the same process, it may be best to wait for @roed314 to fix the development database.

**Comment by proxiex** [comment]
Thank you @jamiesully, I guess I will try what you have suggested while I wait for @roed314  
Gracias!

**Comment by roed314** [comment]
An update on this.  We cleared out a bunch of unused columns, and we just need to copy the schema over to the test database.  @edgarcosta might get to this this weekend (I'm going to be mostly offline); otherwise we'll do it after the holiday on Monday.  I'm sorry for the delay!

**Comment by roed314** [comment]
@proxiex We've just fixed the developer database, so you should be able to follow the instructions in https://github.com/roed314/seminars/blob/master/GettingStarted.md.  Let me know if you run into any issues.  I'm going to close this issue since the original problem has been resolved, but feel free to open another if you run into more issues.

**Comment by roed314** [comment]
@proxiex You'll need the password to connect to the database.  You should email me, since we don't want to post it publicly (see http://math.mit.edu/~roed/#contact for my email).
