### ISSUE TITLE
Math --> Mathematics

### ISSUE THREAD

**Issue by poonen** [roed314/seminars#449]
The top-level subject name should be Mathematics, not Math.  It's more professional that way.  Also, in many countries, "Math" is not even the right way to abbreviate the word.

**Comment by AndrewVSutherland** [comment]
@poonen I changed it on the subject menu a while ago (see #372), where are you still seeing "Math"?

**Comment by poonen** [comment]
@AndrewVSutherland: Sorry, I can't find it anymore.  Maybe I was looking at an old page that wasn't reloaded recently.
I'll close this and mark as duplicate.
