### ISSUE TITLE
Vertical alignment of forminfo

### ISSUE THREAD

**Issue by poonen** [roed314/seminars#450]
Is there a global setting somewhere that is applying
   vertical-align: top;
to every forminfo?  It would be better to make it vertically centered, at least when the forminfo is appearing to the right of an input box, so that it is clearer which box the text is referring to.

**Comment by AndrewVSutherland** [comment]
I'll see if I can tweak style.css to fix this.

**Comment by AndrewVSutherland** [comment]
Done, should be visible on master in < 60 seconds.
