### ISSUE TITLE
Search for conferences - ordering of past conferences

### ISSUE THREAD

**Issue by poonen** [roed314/seminars#465]
On master (but not on researchseminars.org), on the Search page, searching for conferences currently seems to produce one long list that starts with the future conferences in order of start date, followed by past conferences ordered by name.

If both future and past conferences are going to be displayed here, it would make sense to separate them into two tables, and to order past conferences by date in reverse order.

**Comment by AndrewVSutherland** [comment]
It looks like they currently are not sorted (i.e. they are displayed in what ever order they happen to come out of the database, which probably depends on when they were last updated).

I think it would make sense to have separate tabs for future and past conferences, labelled "Conferences" and "Past conferences", just as we do on the browse menu, and order them by start date (forward order for Conferences, reverse order for Past Conference, as  you suggest.

It seems unlikely that you would want to search for both past and future conferences at the same time.  If we add a date search (which I think we should eventually do), we could warn the user if their date range includes dates outside the range of the current tab.

**Comment by AndrewVSutherland** [comment]
Similarly, I think we should add a "Past talks" tab.  Currently there is no way to search for talks in the past!  This actually seems like the thing one might want to search for most often.

**Comment by AndrewVSutherland** [comment]
Nevermind, you can search for talks in the past, you just have to change the date range.  But they are always sorted in forward order.

As an alternative to adding a Past conferences tab, we could add a date range that defaults to a start date of today and no end date (and always order by start date).

In either case, I think it would be good to have the searches on talks and conferences work consistently.

**Comment by poonen** [comment]
I think that your date range solution is better than adding more tabs.  It would be nice to address #419 and #421 at the same time.

**Comment by AndrewVSutherland** [comment]
Great, let's go with date range then.  I can easily address #419 at the same time.  #421 will require a bit more thought, but I'll give it a shot.  I'll do this tomorrow morning.
