### ISSUE TITLE
Date range search on talks not working

### ISSUE THREAD

**Issue by AndrewVSutherland** [roed314/seminars#474]
The only date range search that seems to work at the moment are intervals with no end date,  Searching "Past" or "Next 7 days" or "Next 30 days" or typing in a date range with start and end dates all give a parsing error on the end date:

Error: Could not parse date: '2020-05-18 00:00:00-04:00'

I'm not convinced that using a date range widget is even the right thing here, having separate start and end dates might work better.

**Comment by edgarcosta** [comment]
fixed on live

**Comment by AndrewVSutherland** [comment]
Also fixed in the PR I will be submitting shortly.
