### ISSUE TITLE
Make "logout" more prominent

### ISSUE THREAD

**Issue by poonen** [roed314/seminars#507]
It is a little bit hard to find the logout on the site.

Maybe we could make it a button, and move it to the upper right of the Account page so that it is by itself instead of attached to other text in the middle of the page, and capitalize the first letter?
(I can see why it was put where it is, since it is an operation related to the user name, but for me the need to make it easier to find is more compelling.)

**Comment by poonen** [comment]
I floated it to the right and capitalized the L.
I'm not sure whether making it a button is appropriate.

**Comment by AndrewVSutherland** [comment]
I made it a button, which I think is consistent with the other action buttons on the page and makes it even easier to find.

**Comment by poonen** [comment]
I wonder whether it would look better as a blue text button on a white background, since like the other buttons with this styling, it is usually something that one does not want to press.  What do you think?

**Comment by AndrewVSutherland** [comment]
Yeah, maybe that would be better -- take a look at the logout button on master which now has cancel button styling and let me know what you think.

**Comment by poonen** [comment]
Looks good!
