### ISSUE TITLE
Endorsed users creating content should be required to have a name

### ISSUE THREAD

**Issue by AndrewVSutherland** [roed314/seminars#51]
The list of endorsed users at https://mathseminars.org/user/public/ should list a name and affiliation for each endorsed user (and ideally also a home page).  I just added some missing names from the full_name column of the seminar_organizers table (which exists because not every organizer has a mathseminars account).  In cases where a seminar organizer's email matches that of a user with a mathseminars account, we should check that the names match and warn if they do not.

In general, I don't think we should be posting content on the site created by anonymous users (whether they are curators or organizers).  We could achieve this by not allowing endorsed users to create a seminar or endorse other users until they have filled in their name and affiliation (which could be "none").  Of course this doesn't force anyone to use their real name, but it will at least remind organizers to fill these fields in (with the current setup it is easy to list your name as the organizer of a seminar without realizing your user account has no name).

**Comment by edgarcosta** [comment]
1- https://github.com/roed314/seminars/blob/master/seminars/users/main.py#L568 only endorsed users show on that list
2- think we need to create a document with all the logic for endorsement.
3- at what time I check if they have their name/affiliation filled in? all the time?

**Comment by AndrewVSutherland** [comment]
1. Great, that was my understanding.
2. Definitely, and we should discuss this with @poonen.
3. I would say whenever it is most convenient.  The user can change their name in any case, so from a coding perspective, I think the goal should simply be to make sure the user fills in it at least once (with the current setup they could easily forget and not realize it).

We should have a public set of policies that we expect endorsed users to follow, one of which would be listing their name.  Those policies don't necessarily need to be rigorously enforced by the code (that's why we have human admins), but we should nudge where we can easily do so.

**Comment by AndrewVSutherland** [comment]
https://mathseminars.org/user/public/  now only lists endorsed users that have non-empty names, affiliations, and home pages.  email address are no longer displayed, only links to homepages.
