### ISSUE TITLE
start and end dates for seminars

### ISSUE THREAD

**Issue by edgarcosta** [roed314/seminars#52]
`start_date` and `end_date` were added to the schema, without any code to handle them, and currently are set to None all the time, to avoid breaking the website:
https://github.com/roed314/seminars/blob/6d9672ea825207b8b93d3d28018c536b7d750d01/seminars/seminar.py#L54

we need to fix this at some point

**Comment by roed314** [comment]
I'm working on this.

**Comment by roed314** [comment]
This should be addressed by #61, once that's merged into `live`.
