### ISSUE TITLE
Private seminars visible only to organizers

### ISSUE THREAD

**Issue by AndrewVSutherland** [roed314/seminars#53]
For planning purposes it would be useful for organizers to be able to create a preliminary version of a seminar (or workshop/conference/event) to which they could post talks that would only be visible to organizers of the seminar.

I can imagine two use cases for this:

(1) A private version of a public seminar that the organizers could use to plan future talks that are only to be made public once the speakers and dates are confirmed.  In this use case it would be useful to have the private seminar linked to the public seminar and allow talks in the private seminar to be copied or transferred to the public seminar by pushing a button.

(2) A conference (or workshop/event) that  is initially private but made public once the the organizers are happy with it.  In this use case the entire conference would be simply switch from private to public one the organizers decide to push a "publish" button.

**Comment by roed314** [comment]
Currently we have a notion of "private" which is that is doesn't show up on the browse page or in search results, but will still be displayed with a direct link to the URL.  Is this what you mean by private?  Or do you want a version where the seminar organizers are the only ones even able to access the url?  For the second version I think we would need a new column in the `seminars` schema.

**Comment by poonen** [comment]
On the edit/create seminar page, have a new line 

Visible to [ dropdown menu ]
                  organizers only
                  anyone with the URL
                  all

with all being the default.
Internally there will be six values, because it records also whether the user is endorsed.

On edit/create talk page, 
[toggle] Visible 
with a forminfo saying 
"For a talk to be visible, the seminar must also be set to be visible."

**Comment by gabrielemondello** [comment]
> On the edit/create seminar page, have a new line
> 
> Visible to [ dropdown menu ]
> organizers only
> anyone with the URL
> all
> 
> with all being the default.
> Internally there will be six values, because it records also whether the user is endorsed.
> (At the moment that a user is endorsed, the system changes all these values internally.)
> 
> On edit/create talk page,
> [toggle] Visible
> with a forminfo saying
> "For a talk to be visible, the seminar must also be set to be visible."

Hello,

I cannot find the "visible" option or the "private" one.
Where is it?
I tried to look up in the "create" or "manage" screen, but it seems it's not there.

Thanks!

**Comment by AndrewVSutherland** [comment]
@gabrielemondello This feature has not been implemented yet, this issue will remain open for discussion, suggestions, and updates on progress until it is implemented.

**Comment by gabrielemondello** [comment]
> @gabrielemondello This feature has not been implemented yet, this issue will remain open for discussion, suggestions, and updates on progress until it is implemented.

Ok, sorry for my misunderstanding.
Hope it gets implemented soon!
Thank you!

**Comment by roed314** [comment]
There's a version of this now available on master.mathseminars.org.

**Comment by roed314** [comment]
I've added an item to the FAQ (currently only on master.mathseminars.org); closing.
