### ISSUE TITLE
Advertise to CS community

### ISSUE THREAD

**Issue by edgarcosta** [roed314/seminars#551]
and get in touch with https://cstheorytalks.wordpress.com/

**Comment by poonen** [comment]
I have now notified all the computer scientists who helped us with the topic list.

**Comment by poonen** [comment]
https://www.scottaaronson.com/blog/?p=4805

**Comment by AndrewVSutherland** [comment]
https://twitter.com/fortnow/status/1263545607240761344

**Comment by edgarcosta** [comment]
Sadly the first reply is "It needs to be viewable on a phone. This is 2020, not 2008.".

@kedlaya, have you gotten in touch with Shachar Lovett?
