### ISSUE TITLE
Calendar import for talks with multiple speakers

### ISSUE THREAD

**Issue by rbommel** [roed314/seminars#555]
In my Google calendar, talks with multiple speakers do not look nice. E.g., for the "Panel discussion on hosting virtual events" the title of the panel has become "<a href="https://juliettebruce.github." in my Google calendar.

**Comment by AndrewVSutherland** [comment]
This is a known problem that will be fixed when #222 is addressed (I just bumped this to high priority -- I plan to address it this week).
