### ISSUE TITLE
Option to filter past talks for those that have slides

### ISSUE THREAD

**Issue by AndrewVSutherland** [roed314/seminars#581]
Currently the more filter for past talks has a toggle that lets you filter for those that have video.  I think we should add another toggle for those that have slides.  I realize we do not want to make the more filter overly complicated, but this is a very common use case (possibly more common than searching for videos) and there is currently no way to do this (typing "slides" into the anywhere search does not work and even if it did you would want to be able to combine this binary filter with anywhere searches).

**Comment by roed314** [comment]
This is now on master, along with the ability to filter for talks.
