### ISSUE TITLE
Additional tags for talks on the Browse page

### ISSUE THREAD

**Issue by wenh06** [roed314/seminars#582]
Could you please add additional tags for talks on the Browse page indicating additional requirements for attending the talks, like registering or sending email to organizers to be added to a mail list?

Usually I save the talks by just seeing the speakers' names and titles of the talks. When a talk is about to start, sometimes one just needs to pass a simple exercise to get the password, or even has (almost) free access. However when it requires registering, one would quite probably miss the talk.

**Comment by roed314** [comment]
This was #327, which we perhaps closed a bit early.  We just merged the changes to the live site.  Let us know if you have any other suggestions!
