### ISSUE TITLE
Hide email addresses from bots

### ISSUE THREAD

**Issue by alexjbest** [roed314/seminars#6]
Currently if an organiser is marked as display their email address is visible and can be scraped by bots. We could try and mask this in a way that doesn't inhibit the user too much (a captcha ..?) see https://stackoverflow.com/questions/41318987/hide-email-address-from-bots-keep-mailto perhaps https://mailhide.io/

**Comment by AndrewVSutherland** [comment]
We are going to follow the arXiv model and make emails accessible only to logged in users, which will keep bots from reading them.

**Comment by roed314** [comment]
We have also given users the option to include their homepage, and just went through to update all the organizers.
