### ISSUE TITLE
HTML titles on development branches

### ISSUE THREAD

**Issue by poonen** [roed314/seminars#600]
Would it be possible to have the HTML title of each page reflect the branch it is on?

For instance, 
https://master.researchseminars.org/
would have <title>
master.researchseminars.org - Browse talks
instead of
researchseminars.org - Browse talks

It would help me keep track of which branch I am looking at in my browser (to prevent me from sending a link to master.researchseminars.org to someone, as I just accidentally did).

**Comment by edgarcosta** [comment]
I believe that I addressed this.
