### ISSUE TITLE
Should the two links at the bottom of the Filter knowl open in a new tab?

### ISSUE THREAD

**Issue by poonen** [roed314/seminars#606]
Right now I just edited master to make them do this.  My thinking was that probably the users who click these want to continue working on the Browse page with the Filter knowl open, but want to consult those info pages as they do so.

But I'm not sure that this is the right behavior; that's why I'm asking the question.

**Comment by edgarcosta** [comment]
I think it is weird to open a new tab in this situation. The users themselves can select to open a new tab if they desire.

**Comment by poonen** [comment]
OK.
