### ISSUE TITLE
timezone in knowls in embedded_schedule is always in UTC

### ISSUE THREAD

**Issue by tornaria** [roed314/seminars#614]
After #104, the times in embedded schedule are displayed in seminar timezone, and can be changed with an attribute.

However, this applies only to the times in the schedule, and not to the times inside the knowl for the talk, which are shown in UTC.

For example:
```sh
$ curl -s "https://master.researchseminars.org/seminar/UCSD_NTS/bare?daterange=May%2021&_external" \
    | grep -o ".\{17\}[0-9][0-9]:[0-9][0-9].\{13\}"
<td class="time">14:00</td><td clas
b&gt;Thu May 21, 21:00-22:00 (ended
$ curl -s "https://master.researchseminars.org/seminar/UCSD_NTS/bare?daterange=May%2021&_external&timezone=America/Montevideo" \
    | grep -o ".\{17\}[0-9][0-9]:[0-9][0-9].\{13\}"
<td class="time">18:00</td><td clas
b&gt;Thu May 21, 21:00-22:00 (ended
```
You see in the seminar is at 14:00 (pacific time) or 18:00 (Montevideo time) but the second match (which is taken from the knowl content) always shows 21:00-22:00 which is UTC.

**Comment by edgarcosta** [comment]
I will look into a way of fixing this.

**Comment by edgarcosta** [comment]
@tornaria I looked into this and any of the "easy" fixes that I tried din't work.

It looks like, we will need to change the code and various spots to address this. It is doable, but perhaps but only by the end of the weekend.

**Comment by edgarcosta** [comment]
@tornaria I believe this is fixed.
Please let me know if you encounter any other bugs!
