### ISSUE TITLE
Topics disappear when you press enter while editing a series

### ISSUE THREAD

**Issue by AndrewVSutherland** [roed314/seminars#625]
I have seen this several times but don't know a way to reproduce it.  When it happens, if you go back the topics are there and clicking save again works.  My guess is it is a timing issue.

Screenshot:
![Screenshot from 2020-05-22 08-42-01](https://user-images.githubusercontent.com/11425002/82668898-6c5e1d00-9c08-11ea-89cd-7f5fa34b7319.png)

**Comment by AndrewVSutherland** [comment]
I can now reproduce this.  If you edit a seminar, and change, say, the time in one of the time slots and press enter (not save), the topics all disappear.

**Comment by edgarcosta** [comment]
I can no longer reproduce this. I tried brave, chrome, and firefox on osx.

**Comment by AndrewVSutherland** [comment]
I think this is because I added a save changes button to the top which is now part of the form, so the form gets submitted when you press enter.  Maybe that counts as a fix?  But if you want to reproduce the problem, try removing the save button at the top.

**Comment by edgarcosta** [comment]
Counts as a fix
