### ISSUE TITLE
Spacing above buttons on Account page

### ISSUE THREAD

**Issue by poonen** [roed314/seminars#635]
This is a very minor suggestion, but I think it might look slightly better if the vertical spacing above each of the buttons "Update details" and "Change password" was half as much.

**Comment by AndrewVSutherland** [comment]
I reduced the top margin on the submit buttons a bit, take a look at master (you may need to ctrl-refresh or clear your browser cache to see the new styling).

**Comment by poonen** [comment]
I ctrl-refreshed, but I don't see any change in the spacing.

**Comment by AndrewVSutherland** [comment]
Are you sure you are on master (I see a difference, between

https://master.researchseminars.org/edit/seminar/?shortname=TestSeries

and

https://researchseminars.org/edit/seminar/?shortname=TestSeries

for example, see:

![Screenshot from 2020-05-23 11-35-09](https://user-images.githubusercontent.com/11425002/82734528-81f74380-9ce9-11ea-9ec1-21e65a408763.png)

vs.

![Screenshot from 2020-05-23 11-36-20](https://user-images.githubusercontent.com/11425002/82734557-a521f300-9ce9-11ea-83a1-cc0a84a35c5b.png)

**Comment by poonen** [comment]
The issue was about the _Account_ page, not the Edit series page!  The spacing on the Account page on master has not changed.

**Comment by AndrewVSutherland** [comment]
Ah, the problem is those buttons are not using the right button style so the change did not affect them, I' can fix this now.

**Comment by AndrewVSutherland** [comment]
OK, all save buttons should be using the correct css class and have consistent top margins (previously spacers of various heights were being inserted inconsistently, now there should be no need to use spacers anywhere).

See what you think about the spacing now on master, you might want to look not just at the account page but also edit pages (e.g. series, talk, institution), which should all look the same.

**Comment by poonen** [comment]
OK, it was really only the Account page where the extra space looked funny, but I don't object to the smaller space on the other pages, so your changes are fine.
