### ISSUE TITLE
Remember search box text when switching tabs on Browse page

### ISSUE THREAD

**Issue by poonen** [roed314/seminars#644]
If I enter "Poonen" into the search box on the Browse page, and then I switch from "Talks" to "Past talks", then the search box is cleared and I have to reenter "Poonen".  It would be nice if the search box text were not cleared as one navigates among the tabs on the Browse page.  Ideally it would not clear it even if the search on the original tab had not been carried out yet.

**Comment by AndrewVSutherland** [comment]
On master it will now preserve the keyword between tabs if the search has been performed, so if you want if you type Poonen on the talks browse page, press enter to see future talks by Poonen, then click to Past talks, you will see the past talks by Poonen.  This is now available on master.

It does not save queries that have not yet been performed, which would require more significant changes.

**Comment by AndrewVSutherland** [comment]
Nevermind, I think I have figured out a way to do this properly without too much work.  I'll do that as soon as I get a chance.

**Comment by AndrewVSutherland** [comment]
@poonen I think I have implemented what you want, try it out on master.  Note that it will perform the keyword query when you switch tabs even if it has not been executed, but I think this is less confusing than the alternative.
