### ISSUE TITLE
Font size in blue selection boxes

### ISSUE THREAD

**Issue by poonen** [roed314/seminars#645]
I see that the font in the blue selection boxes (such as for time zone on the Account page) on master is now full size, whereas it was previously smaller.  But the text seems to be constrained to a box within the box, which means that now the bottom of the text gets slightly clipped if it contains a letter such as "g".  It would be nicer if the text were not constrained to that inner box, I think.

**Comment by AndrewVSutherland** [comment]
I reduced the font size a bit, so, at least on my browser, the text stays within the box and I think it looks better, but let me know how it looks to you -- this is on live now.
