### ISSUE TITLE
Periodicity options

### ISSUE THREAD

**Issue by poonen** [roed314/seminars#646]
On the "Edit series" page, currently the options for Periodicity include "weekly", "biweekly", "triweekly", but these could be confusing since "triweekly" often means three times per week.

Can we think of other wording?
Maybe 
"once per week"
"once every two weeks"
"once every three weeks"
?

**Comment by AndrewVSutherland** [comment]
I've made  this change omitting the "once every" (some seminars with biweekly have more than one talk every two weeks and these talks are not necessarily consecutive, and every typically isn't strictly true, e.g. over the summer)

This change will be on master shortly (along with some other changes and bug fixes).  The new options are "weekly", "two weeks", "three weeks".  Eventually I plan to add "monthly" and "two months" (but these require also specifying which week in the month to use).

Note: you can change these by editing the array frequency_options in seminar.py.

**Comment by AndrewVSutherland** [comment]
I changed "two weeks" to "every other week" and "three weeks" to "every third week" which is consistent with the knowl and perhaps clearer.  This is now on master and will be pushed to live later today.
