### ISSUE TITLE
Selecting a language

### ISSUE THREAD

**Issue by poonen** [roed314/seminars#688]
When selecting a language, I would expect that if I type the full name of a language that is in the list and hit return, then that language should be selected.  But this is not what happens now.  I can't even use the keyboard up and down arrows to select the language when there is only one in the list, without using my mouse.

Even better would be if I could type in enough of the language name to narrow it down to one choice and hit return and have that choice be saved.

**Comment by edgarcosta** [comment]
The code used for selecting the language and institution is not written by us, it is certainly possible to modify but is perhaps easier to ask for the original authors: https://github.com/dudyn5ky1/select-pure/issues

**Comment by poonen** [comment]
OK, I did this.
