### ISSUE TITLE
Centering of forminfo on Edit series page

### ISSUE THREAD

**Issue by poonen** [roed314/seminars#691]
On the Edit series page, to the right of "Room", the text "Leave blank if online only" is not vertically centered.  The culprit seems to be the padding-top on the items in that table row.

**Comment by AndrewVSutherland** [comment]
This has been fixed (both on master and live) so that the forminfo is vertically centered, but let me know if you think the padding should not be there at all (I think the intent is to separate the venue information from the date/time information).

**Comment by poonen** [comment]
I think the padding is good there.
