### ISSUE TITLE
Replace "Date" and "Time" headers by "Your time"

### ISSUE THREAD

**Issue by poonen** [roed314/seminars#7]
E.g., at 
https://mathseminars.org/
https://mathseminars.org/search
https://mathseminars.org/edit/schedule/?shortname=STAGE
change the headers  "Date" and "Time" to a single one saying "Your time".

**Comment by AndrewVSutherland** [comment]
Tagging this as critical because it is by the number one source of confusion for new users right now.

**Comment by AndrewVSutherland** [comment]
This has been done on https://mathseminars.org/.  Still working on the other two.

**Comment by AndrewVSutherland** [comment]
This has also been done for https://mathseminars.org/search, and on view seminar.

On "Edit schedule" pages, times are displayed in the seminar's time zone which is displayed above the table, so I don't think a change is needed here (and it seems natural for the organizer to edit the schedule in the seminar's time zone, no matter where they happen to be).
