### ISSUE TITLE
fix the development database

### ISSUE THREAD

**Issue by edgarcosta** [roed314/seminars#702]

**Comment by roed314** [comment]
This should now be functional.

**Comment by jamiesully** [comment]
I'm currently getting the error:

`  File "\seminars\utils.py", line 256, in subject_pairs
    [(rec["subject_id"], rec["name"]) for rec in db.subjects.search({},["subject_id","name"])],
AttributeError: 'PostgresDatabase' object has no attribute 'subjects'`

It looks like the development database still isn't current? 

(Of course I can't discount the possibility that I have something wrong on my end.)

**Comment by roed314** [comment]
The `subject_pairs` function is not currently used anywhere and should be deleted (indeed, `db.subjects` doesn't exist in the normal database.

I'm looking now to see if there are any ways that the development database is out of date.
