### ISSUE TITLE
Do you have plans to write an app for the seminars?

### ISSUE THREAD

**Issue by wenh06** [roed314/seminars#703]
An android app or (and) an ios app, which might could make things more accessable.

**Comment by edgarcosta** [comment]
We have no plans to write an app, however, we have plans to make the website more mobile friendly, we are tracking that issue at #25

**Comment by poonen** [comment]
Even though there is no app, the question was answered with the answer receiving a thumbs up from the original poster, so I am closing this, while keeping #25 open.
