### ISSUE TITLE
Spacing on "View seminar" page

### ISSUE THREAD

**Issue by poonen** [roed314/seminars#71]
Two very minor suggestions for the "View seminar" page:
1) Put a space on each side of the / separating institutions.
2) Consider putting the description on its own line.

See
   https://mathseminars.org/seminar/PPT
for an example where these would be improvements.

**Comment by edgarcosta** [comment]
See if now looks better: https://master.mathseminars.org/seminar/PPT

**Comment by poonen** [comment]
On master.mathseminars.org it looks perfect.  On mathseminars.org it looks as if only 1. has been implemented so far.  Once 2. is there too, feel free to close this.

**Comment by edgarcosta** [comment]
Now on live
