### ISSUE TITLE
Merge the institution "MCM Members Seminar" into "Morningside Center of Mathematics, Chinese Academy of Sciences"

### ISSUE THREAD

**Issue by poonen** [roed314/seminars#72]
The institution 
mcm20200423    MCM Members Seminar
should be deleted or merged into
MCM                     Morningside Center of Mathematics, Chinese Academy of Sciences

Are there any seminars attached to it?  If not, perhaps it can just be deleted, and its creator can be notified.

**Comment by AndrewVSutherland** [comment]
mcm20200423 had no seminars and has been deleted.
