### ISSUE TITLE
On edit pages, move "Chat link" lower in the page

### ISSUE THREAD

**Issue by poonen** [roed314/seminars#738]
On the "Edit talk" page, the "Chat link" entry box should be in the part edited by organizers, not speakers.  The most logical place is the bottom of the "Venue and access" section, just below "View-only livestream".

For uniformity, on the "Edit series" page too I would suggest moving "Chat link" to just below "View-only livestream".

**Comment by AndrewVSutherland** [comment]
This has been done and is now live on master.  Like the live link and stream link the chat_link is now only shown for online talks (including talks that are both offline and online), which I think makes sense (but is not true of the other content links).

Let me know if you want me to change this (but note that if we do it does not make sense for the chat link to sit between the live link and stream link where it is now placed, it should either go above or below all the online only properties).

**Comment by poonen** [comment]
Yes, it's fine to have the chat link only for talks with an online presence.

But I'm not sure why you put the chat link between the interactive and view-only livestreams.  I moved it below both, as I had originally suggested.

**Comment by AndrewVSutherland** [comment]
Sorry I misread your message and agree that below view-only livestream is better, thanks.
