### ISSUE TITLE
Should we display livestream link after the event has ended?

### ISSUE THREAD

**Issue by edgarcosta** [roed314/seminars#789]
From Jonathan Love:
> This may be better addressed to the people behind researchseminars.org, but would it be possible to leave the link for events up even after the listed event end time? There have been several cases of events running long and people trying unsuccessfully to join the event after it officially ends,

**Comment by jonathanrlove** [comment]
Thanks for passing this along Edgar! I do think there is value in removing the link eventually (no need to have months-old zoom links lying around for random people to try out), but even an hour or so of buffer time could be really helpful

**Comment by edgarcosta** [comment]
``is_past`` is the method to edit, see:
https://github.com/roed314/seminars/blob/master/seminars/talk.py#L557
as it is used
https://github.com/roed314/seminars/blob/master/seminars/templates/talk-knowl.html#L50

**Comment by poonen** [comment]
Yes, leave the link up until one hour after the scheduled end time.
