### ISSUE TITLE
We should not actually delete seminars and talks

### ISSUE THREAD

**Issue by AndrewVSutherland** [roed314/seminars#80]
Since we are already versioning changes, we should not actually delete seminars or talks when the user requests this, we should simply write a "deleted" version.  Eventually someone is going to accidentally delete a seminar with hundreds of talks and we should be able to undo a mistake like this.

(in general we should never actually delete anything except user data that a user asks to be deleted).

**Comment by poonen** [comment]
Agree.  What about institutions?

**Comment by AndrewVSutherland** [comment]
We currently don't provide any way to delete institutions, but if/when we do the same should apply.

**Comment by roed314** [comment]
Done.
