### ISSUE TITLE
Past talks in embeddable schedule

### ISSUE THREAD

**Issue by poonen** [roed314/seminars#811]
When a series schedule is embedded in an external webpage and is displaying past talks because there are no future talks, can we change the heading "Time" to "Past times"?  This will make it less confusing in context, I think.

**Comment by edgarcosta** [comment]
I went with past times.
If you prefer something else, here is the file to edit:
https://github.com/roed314/seminars/blob/master/seminars/templates/seminar_bare.html#L9
