### ISSUE TITLE
Contact asterisk not being displayed correctly?

### ISSUE THREAD

**Issue by AndrewVSutherland** [roed314/seminars#820]
On the seminar https://researchseminars.org/seminar/OneWorldPDE two of the three organizers are endorsed users with confirmed emails, but only one has a contact asterisk (there are several similar examples).

I don't understand why this is the case, it looks like a bug to m (but maybe I am missing something).

**Comment by edgarcosta** [comment]
This is a bug, as they are all set as organizers. I don't understand what
is going on.

**Comment by AndrewVSutherland** [comment]
This is not an isolated example, also see https://researchseminars.org/seminar/MITCategories, which currently has no contact listed (but the save seminar code was happy that there was a visible contact, otherwise it would have complained when I removed myself as a visible curator).  The bug seems to only be in the display.

**Comment by AndrewVSutherland** [comment]
@edgarcosta Note that it is not enough for them to be marked as organizers, they also need to be organizers with a confirmed email address, but this is they case for at least one organizer that is not marked as a contact in both of these examples.

**Comment by edgarcosta** [comment]
this was a case of not doing case insensitive matching

**Comment by AndrewVSutherland** [comment]
Great, thanks for sorting this!
