### ISSUE TITLE
confusing wording for livestream links and meeting links

### ISSUE THREAD

**Issue by edgarcosta** [roed314/seminars#826]
see image
![Screen Shot 2020-09-02 at 12 56 30](https://user-images.githubusercontent.com/322822/92015046-31e34080-ed1e-11ea-9436-ceb54bd15a20.png)

**Comment by AndrewVSutherland** [comment]
Yup, that is pretty confusing!

**Comment by AndrewVSutherland** [comment]
Probably we should change the words "Livestream link" to "Interactive link" in this situation.  But I'm also thinking that maybe we should add another access control option for organizers who only post view-only links (e.g. YouTube livestreams); there are a number of seminars that do this.
