### ISSUE TITLE
"Online" slider on the Search page

### ISSUE THREAD

**Issue by poonen** [roed314/seminars#84]
When at the Search page, searching for seminars, the "Online" slider seems to do nothing.

**Comment by roed314** [comment]
Well, basically all of our seminars are currently online.  Did you try creating a test seminar that isn't online and searching to see if it came up?

I guess the non-obvious thing is that "online" means "require an online presence" rather than having it being unchecked mean "exclude seminars that are online."

**Comment by poonen** [comment]
The problem is as you guessed, that I had assumed that unchecked meant "exclude online talks".  The slider should be labelled "Online only" to clarify this.

**Comment by edgarcosta** [comment]
We have decided that this will become a select named:
"Venue", with the options "", "online", "offline".

**Comment by poonen** [comment]
There are 3 types of talks: online only, offline only, online+offline.
There are therefore 2^3 types of searches one could do, depending on which subsets of these types you want included in the search results.  I don't know which subsets "", "online", "offline" refer to - this seems pretty confusing to me.

**Comment by poonen** [comment]
I'm not saying that we need to include the ability to do all 2^3 searches.  I'm just trying to make the point that the behavior of your labels is ambiguous.

**Comment by roed314** [comment]
I think the useful searches are "has an online presence", "has an offline presence" and "no constraint".  I welcome better language for what to put in the select dropdown.

**Comment by poonen** [comment]
Maybe it's impossible to explain that with short words.  Offline sounds too much like the complement of online.

Maybe in the dropdown menu use
   online
   in-person
   any
with the default being any, and then include a knowl on the word "Venue" with the following explanation?

     Selecting "online" limits search results talks that are accessible online.
     Selecting "in-person" limits search results to talks that exist as an in-person meeting; some of these may also be accessible online.
     Selecting "any" places no constraint.

**Comment by edgarcosta** [comment]
@poonen, we have implemented what you suggested, but for the time being David and I decided t omit the option, as many seminars have a room set, and we don't want to be claiming that are meeting in person.
