### ISSUE TITLE
embedded table does not fully extend

### ISSUE THREAD

**Issue by markusrademacher** [roed314/seminars#848]
First of all many thanks to the creators for this great tool which is just awesome and is a gamechanger when it comes to the admin/organisation side of hosting seminars. Unfortunately I have the following issue: 
I tried to implement the table of upcoming seminars on the seminar's external wordpress website with mixed success. (https://www.optomechanics.net/?page_id=83) While I got the general table to work. It does seem to not fully extend for an individual talk. I attach a sceenshot to illustrate the issue. It unfortunately cuts the talk description off right before the valuable links to the livestreams are listed. 
<img width="425" alt="Screenshot 2020-10-06 at 15 38 59" src="https://user-images.githubusercontent.com/17744524/95216623-32259e80-07ea-11eb-8c8e-714d0c031531.png">

So I have two questions: 

- How can I fix the issue of having the individual talk item not fully extended?
- Is it possible to place the links to the live stream at a more prominent position rather than right at the end of the extended talk item description in the embedded table? For instance right below the speaker's name, like it is done in the layout for the individual talk site on researchseminars.org (https://researchseminars.org/talk/UniKORNseminars/1/).

Thanks for everyone's help in advance.

**Comment by edgarcosta** [comment]
@markusrademacher, the first issue of the talk not fully extending is now fixed.
I have created a new issue #850 for your second point.

I also recommend adding `style="width: 120%;"` 
```
<div class="embedded_schedule" shortname="UniKORNseminars" daterange="future">
```
becoming
```
<div class="embedded_schedule" shortname="UniKORNseminars" daterange="future" style="width: 120%;">
```
as your current style is making the table quite narrow.
