### ISSUE TITLE
Display the talk for up to one hour after the start time in the embedded future talk's table 

### ISSUE THREAD

**Issue by markusrademacher** [roed314/seminars#851]
Unfortunately the current talk is moved from the embedded future talks table to the embedded past talks table as soon as the talk has started, i.e. 1 minute after the talk's start time. This seems to be a problem in particular related to the embedded tables because on the seminar series page, where the talk was hosted on the researchseminars.org website, it was still displayed in bold in the upcoming talks table after 50 minutes past the start time.  

Is it therefore possible to have the current talk displayed for up to one hour after the start time in the embedded future talk's table in order for people to join late via the livestream link in the embedded schedule on the external website?

**Comment by edgarcosta** [comment]
We will now future talks and ongoing talks.

Might be also worthwhile that the argument `daterange` can also be date range, e.g.:
`Jan 1, 2020 - Nov 1, 2020`
