### ISSUE TITLE
ability to add a chair to a talk 

### ISSUE THREAD

**Issue by markusrademacher** [roed314/seminars#853]
Please add the ability to assign a session chair to a specific talk of a series. Ideally the chair's name would also be displayed in the talk's description.

**Comment by AndrewVSutherland** [comment]
@markusrademacher You can list the session chair in the talk comments; see 

    https://researchseminars.org/talk/ANTS14/1/

for example.  We debated adding a separate field for this but decided it wasn't worth cluttering the edit talk page with another data entry item.
