### ISSUE TITLE
ORCID regex not correct

### ISSUE THREAD

**Issue by alexjbest** [roed314/seminars#856]
I tried to add my orcid but the site reports that it is invalid as the ORCID regex in the database is

`^[0-9][0-9][0-9][0-9]-[0-9][0-9][0-9][0-9]-[0-9][0-9][0-9][0-9]-[0-9][0-9][0-9][0-9]$`

however orcid's final checksum digit can be an X, so a better regex would be

`^\d{4}\-\d{4}\-\d{4}\-\d{3}(?:\d|X)$`

I'm not sure I have the db permissions to change this myself.

**Comment by AndrewVSutherland** [comment]
Fixed.
