### ISSUE TITLE
Use API to retrieve link to edit page

### ISSUE THREAD

**Issue by kedlaya** [roed314/seminars#866]
My seminar workflow has been to email speakers an edit link so that they can post their own title/abstract, which I then retrieve via the API. However, I would also like to use the API to help me generate these emails, which means I need 'edit_link' to be a field I can query for (using the API token).

**Comment by edgarcosta** [comment]
@kedlaya, #873 will allow you get all the columns if you authenticate and you can edit the seminar (of the talk) that you are looking up

**Comment by edgarcosta** [comment]
@kedlaya, please let us know if you find any issues
