### ISSUE TITLE
Switiching license to AGPL

### ISSUE THREAD

**Issue by edgarcosta** [roed314/seminars#880]
We are planning to switch license from GPL to AGPL.

Quoting MongoDB:

> With traditional GPL, copyleft was associated with the concept of distribution of software.  The problem is that nowadays, distribution of software is rare: things tend to run in the cloud.  AGPL fixes this “loophole” in GPL by saying that if you use the software over a network, you are bound by the copyleft.  Other than that, the license is virtually the same as GPL v3.

I already got a yes from @AndrewVSutherland  and @roed314 
For that we need a yay from all the contributors:
- @alexjbest 
- @davidlowryduda 
- @everthemore 
- @poonen
- @jamiesully 
- @duetosymmetry 
- @tornaria 

If you agree, please let us know.

**Comment by duetosymmetry** [comment]
I agree to this license change.

**Comment by alexjbest** [comment]
Fine with me

**Comment by everthemore** [comment]
No objections from my side, I agree.
For what it is worth: I hardly qualify as a contributor; you have my
explicit consent for any future such questions :)

**Comment by davidlowryduda** [comment]
I agree.

**Comment by tornaria** [comment]
I agree.

As a matter of fact, I don't think I have any claim to anything here, but in case I do I grant all of it to @edgarcosta and @roed314 to do as they wish.

**Comment by jamiesully** [comment]
I agree.

**Comment by edgarcosta** [comment]
I got the yay from everyone

**Comment by AndrewVSutherland** [comment]
I see this issue was closed, but it doesn't look like the license file has been changed.
