### ISSUE TITLE
Start time before end time

### ISSUE THREAD

**Issue by poonen** [roed314/seminars#92]
At https://mathseminars.org/edit/schedule/?shortname=testseminar
there is a talk from 22:00 to 01:00 the next day in Central Time
(the talk itself is in Alaska Time), which should be fine.

But when I click Refresh, I get an error 
"Error: Your start time is after your end time; perhaps you forgot pm".

Even worse, I get the error when I try to click "Details" to edit the talk.

**Comment by AndrewVSutherland** [comment]
I think a reasonable fix for this is to display warnings for talks that seem unrealistically long (more than 8 hours, say), but not complain about an end time of day that precedes that start time of day.  So 22:00 to 1:00 would not trigger a warning but 10:00 to 1:00 would.

And there should never be errors that prevent you from editing or viewing something.

**Comment by poonen** [comment]
@AndrewVSutherland: That sounds like a good idea. So I guess that on the edit schedule page, the end time would always be interpreted as the next time after the start time, even if it would be on a different day.  So 16:00-15:00 would be interpreted as a 23-hour seminar and would trigger a warning.

**Comment by AndrewVSutherland** [comment]
@poonen Yes, that is what I had in mind -- I can implement this later today.

**Comment by AndrewVSutherland** [comment]
This is now fixed on master but we need to fix a few unrelated issues before updating the live site.
