### ISSUE TITLE
API for adding talks to seminars

### ISSUE THREAD

**Issue by roed314** [roed314/seminars#96]
It would be nice to be able to update seminars and talks using an API.  For talks, we already have a token that could be used for authentication; for seminars we would need to add a token for this purpose.

My inclination would be to use json to pass objects to and from an external user.  When we receive requests to update the database, we would need to validate the data, authenticate, then save to the database.  There should probably also be rate limiting for API requests as well.

**Comment by roed314** [comment]
A first version of an API is now available, with documentation at researchseminars.org/api.  It's currently only active for approved users; if anyone is following this issue and wants to be added feel free to email us.

**Comment by poonen** [comment]
My understanding is that this is complete, so I'm closing it, but feel free to reopen if there is more to do.  By the way, I looked at some of the tables resulting from the code on the API page, and they look great!
